[package]
name = "aurix-db"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aurix-common = { path = "../aurix-common" }
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }