"""Helpers shared by the emitters."""

from __future__ import annotations

import textwrap
from typing import Iterable, List, Optional

from ir import Api, Operation, TypeRef

HEADER = "Generated by tools/openapi-sdk/generate.py from api/openapi.json (Aurix {version}). Do not edit."


def header(api: Api, comment: str) -> str:
    return f"{comment} {HEADER.format(version=api.version)}\n"


def wrap(text: str, width: int = 96) -> List[str]:
    out: List[str] = []
    if not text or not text.strip():
        return out
    for para in text.strip().split("\n"):
        if not para.strip():
            out.append("")
            continue
        out.extend(textwrap.wrap(para, width=width) or [""])
    return out


def op_doc_lines(op: Operation) -> List[str]:
    lines: List[str] = []
    if op.summary:
        lines.append(op.summary.rstrip("."))
        lines.append("")
    if op.description:
        lines.extend(wrap(op.description))
        lines.append("")
    lines.append(f"`{op.method} {op.path}`")
    if op.security:
        lines.append("Auth: " + " | ".join(op.security) + ".")
    if op.permissions:
        lines.append("Permissions: " + ", ".join(op.permissions) + ".")
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def raw_variant(op: Operation) -> str:
    """json → typed only; mixed → typed + raw; binary/text → raw only."""
    if op.response_kind != "json":
        return "raw"
    if any(m != "application/json" for m in op.response_media):
        return "both"
    return "typed"


def mixed_note(op: Operation) -> Optional[str]:
    others = [m for m in op.response_media if m != "application/json"]
    if raw_variant(op) == "both":
        return f"When the server answers with {', '.join(others)} (non-JSON `format`) this call fails; use the `Raw` variant instead."
    return None


def group_by_tag(ops: Iterable[Operation]):
    groups = {}
    for op in ops:
        groups.setdefault(op.tag, []).append(op)
    return groups


def is_scalar(t: TypeRef) -> bool:
    return t.kind in ("string", "integer", "number", "boolean", "enum")
