<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <RootNamespace>Aurix.Examples.TokenServer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../csharp/Aurix.Server/Aurix.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TokenServer.Tests" />
  </ItemGroup>

</Project>
