// Generated by tools/openapi-sdk/generate.py from api/openapi.json (Aurix 1.4.0). Do not edit.

package aurix

import (
	"context"
	"encoding/json"
	"net/url"
	"strconv"
)

var (
	_ = json.RawMessage(nil)
	_ = strconv.Itoa
)

// Health — Liveness and basic counters
//
// `GET /health`
func (c *Client) Health(ctx context.Context, opts ...RequestOption) (*Health, error) {
	var q url.Values
	var out Health
	if err := c.doJSON(ctx, "GET", "/health", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// Ready — Readiness (database and Redis reachable)
//
// `GET /ready`
func (c *Client) Ready(ctx context.Context, opts ...RequestOption) (*Ready, error) {
	var q url.Values
	var out Ready
	if err := c.doJSON(ctx, "GET", "/ready", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// Openapi — This document
//
// `GET /openapi.json`
func (c *Client) Openapi(ctx context.Context, opts ...RequestOption) (map[string]any, error) {
	var q url.Values
	var out map[string]any
	err := c.doJSON(ctx, "GET", "/openapi.json", q, nil, &out, opts)
	return out, err
}

// AdminSetup — Bootstrap the first superadmin
//
// Allowed only while no administrator exists, or when `X-Bootstrap-Token` matches
// `auth.bootstrap_token`. Rate-limited by client IP.
//
// `POST /admin/setup`
// Auth: BootstrapToken.
func (c *Client) AdminSetup(ctx context.Context, body BootstrapAdminRequest, opts ...RequestOption) (*Admin, error) {
	var q url.Values
	var out Admin
	if err := c.doJSON(ctx, "POST", "/admin/setup", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminLogin — Exchange email + password for an admin JWT
//
// `POST /admin/login`
func (c *Client) AdminLogin(ctx context.Context, body AdminLoginRequest, opts ...RequestOption) (*AdminLoginResponse, error) {
	var q url.Values
	var out AdminLoginResponse
	if err := c.doJSON(ctx, "POST", "/admin/login", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminAuthMethods — Sign-in methods offered by this deployment
//
// For login pages: whether password login is on and whether (and where) SSO starts.
//
// `GET /admin/auth/methods`
func (c *Client) AdminAuthMethods(ctx context.Context, opts ...RequestOption) (*AdminAuthMethods, error) {
	var q url.Values
	var out AdminAuthMethods
	if err := c.doJSON(ctx, "GET", "/admin/auth/methods", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminOIDCCallback — SSO callback (identity provider redirect target)
//
// Verifies `state` (encrypted, single-use, bound to the login cookie, expires after
// `auth.oidc.state_ttl_secs`), exchanges `code` (PKCE), validates the ID token (signature via the
// provider's JWKS, `iss`, `aud`, `nonce`, `exp`, email verification, allowed domains) and maps the
// provider's groups to a role. With `auth.oidc.frontend_redirect` set, the browser is sent there
// with `#token=…&expires_in_secs=…[&return_to=…]` (or `#error=…&error_description=…`); otherwise
// the token is returned as JSON. The login cookie is cleared either way. Roles come from
// `auth.oidc.superadmin_emails`, then the highest role in `role_mapping` matched by the groups
// claim, then `default_role`; identities that resolve to no role are refused (`403`).
//
// `GET /admin/oidc/callback`
func (c *Client) AdminOIDCCallback(ctx context.Context, query *AdminOidcCallbackQuery, opts ...RequestOption) (*AdminOidcCallbackResponse, error) {
	q := url.Values{}
	if query != nil {
		if query.Code != nil {
			q.Set("code", *query.Code)
		}
		if query.State != nil {
			q.Set("state", *query.State)
		}
		if query.Error != nil {
			q.Set("error", *query.Error)
		}
		if query.ErrorDescription != nil {
			q.Set("error_description", *query.ErrorDescription)
		}
	}
	var out AdminOidcCallbackResponse
	if err := c.doJSON(ctx, "GET", "/admin/oidc/callback", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminMe — Current administrator
//
// The account as stored now (role, permissions, SSO binding). `auth_source` reflects how the
// presented token was obtained.
//
// `GET /admin/me`
// Auth: AdminToken.
func (c *Client) AdminMe(ctx context.Context, opts ...RequestOption) (*Admin, error) {
	var q url.Values
	var out Admin
	if err := c.doJSON(ctx, "GET", "/admin/me", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminChangeOwnPassword — Change own password
//
// Revokes every token issued to the caller so far, including the one used for this call — sign in
// again afterwards.
//
// `POST /admin/me/password`
// Auth: AdminToken.
func (c *Client) AdminChangeOwnPassword(ctx context.Context, body ChangeOwnPasswordRequest, opts ...RequestOption) (*TokensRevoked, error) {
	var q url.Values
	var out TokensRevoked
	if err := c.doJSON(ctx, "POST", "/admin/me/password", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminLogoutAll — Sign out everywhere
//
// Revokes every token issued to the caller so far.
//
// `POST /admin/logout-all`
// Auth: AdminToken.
func (c *Client) AdminLogoutAll(ctx context.Context, opts ...RequestOption) (*TokensRevoked, error) {
	var q url.Values
	var out TokensRevoked
	if err := c.doJSON(ctx, "POST", "/admin/logout-all", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAdmins — List administrators
//
// `GET /admin/admins`
// Auth: AdminToken.
func (c *Client) ListAdmins(ctx context.Context, opts ...RequestOption) (*ListAdminsResponse, error) {
	var q url.Values
	var out ListAdminsResponse
	if err := c.doJSON(ctx, "GET", "/admin/admins", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateAdmin — Create an administrator
//
// Creates a password account. SSO accounts are provisioned on their first SSO login instead
// (`auth.oidc.auto_provision`).
//
// `POST /admin/admins`
// Auth: AdminToken.
func (c *Client) CreateAdmin(ctx context.Context, body CreateAdminRequest, opts ...RequestOption) (*Admin, error) {
	var q url.Values
	var out Admin
	if err := c.doJSON(ctx, "POST", "/admin/admins", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAdmin — Get an administrator
//
// `GET /admin/admins/{admin_id}`
// Auth: AdminToken.
func (c *Client) GetAdmin(ctx context.Context, adminID string, opts ...RequestOption) (*Admin, error) {
	var q url.Values
	var out Admin
	if err := c.doJSON(ctx, "GET", "/admin/admins/"+url.PathEscape(adminID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateAdmin — Update role, display name or active state
//
// `PATCH /admin/admins/{admin_id}`
// Auth: AdminToken.
func (c *Client) UpdateAdmin(ctx context.Context, adminID string, body UpdateAdminRequest, opts ...RequestOption) (*Admin, error) {
	var q url.Values
	var out Admin
	if err := c.doJSON(ctx, "PATCH", "/admin/admins/"+url.PathEscape(adminID), q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ResetAdminPassword — Reset an administrator's password
//
// Sets a new password (also for SSO-provisioned accounts) and revokes the target's tokens.
//
// `POST /admin/admins/{admin_id}/password`
// Auth: AdminToken.
func (c *Client) ResetAdminPassword(ctx context.Context, adminID string, body ResetAdminPasswordRequest, opts ...RequestOption) (*TokensRevoked, error) {
	var q url.Values
	var out TokensRevoked
	if err := c.doJSON(ctx, "POST", "/admin/admins/"+url.PathEscape(adminID)+"/password", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// RevokeAdminTokens — Sign an administrator out everywhere
//
// Revokes every token issued to the target so far; the account stays active.
//
// `POST /admin/admins/{admin_id}/logout-all`
// Auth: AdminToken.
func (c *Client) RevokeAdminTokens(ctx context.Context, adminID string, opts ...RequestOption) (*TokensRevoked, error) {
	var q url.Values
	var out TokensRevoked
	if err := c.doJSON(ctx, "POST", "/admin/admins/"+url.PathEscape(adminID)+"/logout-all", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminAuditLog — Audit log across all applications
//
// `GET /admin/audit-log`
// Auth: AdminToken.
func (c *Client) AdminAuditLog(ctx context.Context, query *AdminAuditLogQuery, opts ...RequestOption) ([]AuditLogEntry, error) {
	q := url.Values{}
	if query != nil {
		if query.Page != nil {
			q.Set("page", strconv.FormatInt(*query.Page, 10))
		}
		if query.PerPage != nil {
			q.Set("per_page", strconv.FormatInt(*query.PerPage, 10))
		}
	}
	var out []AuditLogEntry
	err := c.doJSON(ctx, "GET", "/admin/audit-log", q, nil, &out, opts)
	return out, err
}

// AdminEffectiveConfig — Effective configuration of this node (secrets redacted)
//
// The configuration the answering node runs with, after file, environment and defaults were merged
// — read-only. Every credential is masked: fields named like `*secret*`, `*password*`, `*_key`,
// `api_key`, `*_token` become `"***"` when set, and `user:password@` in URLs (database, Redis,
// sentinels, endpoints) is masked. File paths, ports, flags and timings are returned verbatim.
// Node-local: behind a load balancer, address the node you want to inspect (`api_url` in `GET
// /v1/nodes`). Nodes are configured through files/env/Helm; there is deliberately no write
// counterpart.
//
// `GET /admin/config`
// Auth: AdminToken.
func (c *Client) AdminEffectiveConfig(ctx context.Context, opts ...RequestOption) (*EffectiveConfig, error) {
	var q url.Values
	var out EffectiveConfig
	if err := c.doJSON(ctx, "GET", "/admin/config", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetentionSweep — Run a retention sweep now
//
// Applies the `[retention]` rules immediately. The sweep holds a PostgreSQL advisory lock so only
// one node runs it at a time.
//
// `POST /admin/retention/sweep`
// Auth: AdminToken.
func (c *Client) RetentionSweep(ctx context.Context, opts ...RequestOption) (*SweepReport, error) {
	var q url.Values
	var out SweepReport
	if err := c.doJSON(ctx, "POST", "/admin/retention/sweep", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminUsage — Usage totals of every application
//
// Range totals per application across the fleet (applications without usage in the range are
// omitted). Default range: the last 30 days.
//
// `GET /admin/analytics/usage`
// Auth: AdminToken.
func (c *Client) AdminUsage(ctx context.Context, query *AdminUsageQuery, opts ...RequestOption) (*FleetUsage, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
	}
	var out FleetUsage
	if err := c.doJSON(ctx, "GET", "/admin/analytics/usage", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminAppUsage — One application's series, totals and quota state
//
// The same body as `GET /v1/analytics` for the given application, plus `app_id`, `active` and its
// `quota`. Deactivated (deleted) applications are still returned so their last invoice can be
// produced; `404` only for an unknown id.
//
// `GET /admin/analytics/apps/{app_id}`
// Auth: AdminToken.
func (c *Client) AdminAppUsage(ctx context.Context, appID string, query *AdminAppUsageQuery, opts ...RequestOption) (*AdminAppUsage, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
		if query.Step != nil {
			q.Set("step", strconv.FormatInt(*query.Step, 10))
		}
	}
	var out AdminAppUsage
	if err := c.doJSON(ctx, "GET", "/admin/analytics/apps/"+url.PathEscape(appID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminExportUsage — 5-minute buckets of every application (JSON or CSV)
//
// Fleet-wide export of application buckets (`scope=fleet`), same row shape and cap as `GET
// /v1/analytics/export`. Default range: the last 30 days.
//
// `GET /admin/analytics/export`
// Auth: AdminToken.
//
// When the server answers with text/csv (non-JSON `format`) this call fails; use the `AdminExportUsageRaw` instead.
func (c *Client) AdminExportUsage(ctx context.Context, query *AdminExportUsageQuery, opts ...RequestOption) (*UsageExport, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
		if query.Format != nil {
			q.Set("format", string(*query.Format))
		}
	}
	var out UsageExport
	if err := c.doJSON(ctx, "GET", "/admin/analytics/export", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdminExportUsageRaw — 5-minute buckets of every application (JSON or CSV)
//
// Fleet-wide export of application buckets (`scope=fleet`), same row shape and cap as `GET
// /v1/analytics/export`. Default range: the last 30 days.
//
// `GET /admin/analytics/export`
// Auth: AdminToken.
//
// Returns the raw body (application/json, text/csv).
func (c *Client) AdminExportUsageRaw(ctx context.Context, query *AdminExportUsageQuery, opts ...RequestOption) (*RawResponse, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
		if query.Format != nil {
			q.Set("format", string(*query.Format))
		}
	}
	return c.doRaw(ctx, "GET", "/admin/analytics/export", q, nil, opts, "*/*")
}

// ListApps — List applications
//
// `GET /v1/apps`
// Auth: AdminToken.
func (c *Client) ListApps(ctx context.Context, query *ListAppsQuery, opts ...RequestOption) (*ListAppsResponse, error) {
	q := url.Values{}
	if query != nil {
		if query.Page != nil {
			q.Set("page", strconv.FormatInt(*query.Page, 10))
		}
		if query.PerPage != nil {
			q.Set("per_page", strconv.FormatInt(*query.PerPage, 10))
		}
	}
	var out ListAppsResponse
	if err := c.doJSON(ctx, "GET", "/v1/apps", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateApp — Create an application (tenant)
//
// Returns the application's first API key with all permissions; it is shown only once.
//
// `POST /v1/apps`
// Auth: AdminToken.
func (c *Client) CreateApp(ctx context.Context, body CreateAppRequest, opts ...RequestOption) (*CreatedApp, error) {
	var q url.Values
	var out CreatedApp
	if err := c.doJSON(ctx, "POST", "/v1/apps", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetApp — Application with channel and session counts
//
// `GET /v1/apps/{app_id}`
// Auth: AdminToken.
func (c *Client) GetApp(ctx context.Context, appID string, opts ...RequestOption) (*AppDetail, error) {
	var q url.Values
	var out AppDetail
	if err := c.doJSON(ctx, "GET", "/v1/apps/"+url.PathEscape(appID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateApp — Edit an application's name, description or quotas
//
// Fields left out are unchanged; `description: null` clears it. Raising
// `max_participants_per_channel` is how an existing application gets large (audience) channels —
// `POST /v1/channels` clamps `config.max_participants` to this quota. Lowering it affects channels
// created or reconfigured afterwards. `max_concurrent_sessions` and `monthly_participant_minutes`
// (0 = unlimited) take effect on new sessions/joins within `usage.quota_cache_secs`; existing
// sessions are not cut.
//
// `PATCH /v1/apps/{app_id}`
// Auth: AdminToken.
func (c *Client) UpdateApp(ctx context.Context, appID string, body UpdateAppRequest, opts ...RequestOption) (*App, error) {
	var q url.Values
	var out App
	if err := c.doJSON(ctx, "PATCH", "/v1/apps/"+url.PathEscape(appID), q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteApp — Deactivate an application
//
// Soft-deletes the app: its API keys stop authenticating at once, every live session is closed on
// every node, and its usage history stays readable through `/admin/analytics`. Deleting an already
// deactivated or unknown application returns 404.
//
// `DELETE /v1/apps/{app_id}`
// Auth: AdminToken.
func (c *Client) DeleteApp(ctx context.Context, appID string, opts ...RequestOption) (*DeleteAppResponse, error) {
	var q url.Values
	var out DeleteAppResponse
	if err := c.doJSON(ctx, "DELETE", "/v1/apps/"+url.PathEscape(appID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// RotateAppKey — Issue a new full-permission API key for an application
//
// Existing keys keep working until revoked through `DELETE /v1/api-keys/{key_id}`.
//
// `POST /v1/apps/{app_id}/rotate-key`
// Auth: AdminToken.
func (c *Client) RotateAppKey(ctx context.Context, appID string, opts ...RequestOption) (*RotateAppKeyResponse, error) {
	var q url.Values
	var out RotateAppKeyResponse
	if err := c.doJSON(ctx, "POST", "/v1/apps/"+url.PathEscape(appID)+"/rotate-key", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNodes — Media node fleet
//
// Every node registers itself and heartbeats; nodes silent for 30 s are marked unhealthy. `drain`
// is set while an operator drains the node.
//
// `GET /v1/nodes`
// Auth: AdminToken.
func (c *Client) ListNodes(ctx context.Context, opts ...RequestOption) ([]MediaNode, error) {
	var q url.Values
	var out []MediaNode
	err := c.doJSON(ctx, "GET", "/v1/nodes", q, nil, &out, opts)
	return out, err
}

// ListNodeLinks — Measured cascade links
//
// Every node probes its cascade peers (UDP first, TCP fallback when UDP stops answering) and
// publishes the links it confirmed. One row per `(node_id, peer_id)` as seen from `node_id`; a
// pair missing in both directions while both nodes publish tables is unreachable. The
// `region_tree` topology planner ranks hubs by these RTTs and routes around unreachable pairs.
// Rows older than a few `media.cascade_discovery_interval_ms` periods are stale (the node stopped
// publishing).
//
// `GET /v1/nodes/links`
// Auth: AdminToken.
func (c *Client) ListNodeLinks(ctx context.Context, opts ...RequestOption) ([]MediaNodeLink, error) {
	var q url.Values
	var out []MediaNodeLink
	err := c.doJSON(ctx, "GET", "/v1/nodes/links", q, nil, &out, opts)
	return out, err
}

// DrainNode — Drain a node (maintenance)
//
// Marks the node as draining, fleet-wide and persistently (survives restarts and heartbeats) until
// `undrainNode`. A draining node keeps the sessions it hosts and still accepts their reconnects
// (resume), but takes no fresh sessions and adopts no sessions from other nodes (`/ws` answers
// `503` to both; clients move to the next failover endpoint), is left out of failover endpoints
// handed to other nodes' clients and of region discovery. It does not change the node's health or
// configuration; to empty it, watch `active_participants` in `GET /v1/nodes` and stop the node
// when it reaches 0 (or earlier — remaining clients then resume on another node through failover).
// Audited as `node_drained`.
//
// `POST /v1/nodes/{node_id}/drain`
// Auth: AdminToken.
func (c *Client) DrainNode(ctx context.Context, nodeID string, body *DrainNodeRequest, opts ...RequestOption) (*MediaNode, error) {
	var q url.Values
	var bodyArg any
	if body != nil {
		bodyArg = body
	}
	var out MediaNode
	if err := c.doJSON(ctx, "POST", "/v1/nodes/"+url.PathEscape(nodeID)+"/drain", q, bodyArg, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// UndrainNode — End a node drain
//
// Makes the node eligible for fresh sessions, failover and region discovery again. Audited as
// `node_undrained`.
//
// `POST /v1/nodes/{node_id}/undrain`
// Auth: AdminToken.
func (c *Client) UndrainNode(ctx context.Context, nodeID string, opts ...RequestOption) (*MediaNode, error) {
	var q url.Values
	var out MediaNode
	if err := c.doJSON(ctx, "POST", "/v1/nodes/"+url.PathEscape(nodeID)+"/undrain", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// IssueToken — Issue a player session token
//
// Creates or looks up the user by `external_id` and returns a session JWT with the channel grants.
// Call this from your game backend; never ship API keys to clients.
//
// `POST /v1/tokens`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: tokens:issue.
func (c *Client) IssueToken(ctx context.Context, body GenerateTokenRequest, opts ...RequestOption) (*TokenResponse, error) {
	var q url.Values
	var out TokenResponse
	if err := c.doJSON(ctx, "POST", "/v1/tokens", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// IssueActionToken — Issue a one-time action token
//
// `login` opens a session, `join` enters one channel, `kick`/`mute`/`unmute` authorise a single
// moderation act (these three additionally need `moderation:write`). Each token is bound to a
// `jti` that is consumed atomically on first use. With `auth.require_action_tokens = true` session
// JWTs alone can no longer open sessions or join channels.
//
// `POST /v1/tokens/action`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: tokens:issue, moderation:write (kick/mute/unmute).
func (c *Client) IssueActionToken(ctx context.Context, body ActionTokenRequest, opts ...RequestOption) (*ActionTokenResponse, error) {
	var q url.Values
	var out ActionTokenResponse
	if err := c.doJSON(ctx, "POST", "/v1/tokens/action", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRegions — Region discovery for the game backend
//
// One entry per region with at least one healthy, non-saturated node that advertises a public
// WebSocket URL, carrying that region's least-loaded node. Use it to choose the region before
// minting a token, or pass `region`/`location` straight to `POST /v1/tokens` and read `endpoint`.
// Served from the node registry, which follows the fleet's heartbeats with at most ~15 s of lag.
//
// `GET /v1/regions`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: tokens:issue.
func (c *Client) ListRegions(ctx context.Context, query *ListRegionsQuery, opts ...RequestOption) (*RegionsResponse, error) {
	q := url.Values{}
	if query != nil {
		if query.Region != nil {
			q.Set("region", string(*query.Region))
		}
		if query.Latitude != nil {
			q.Set("latitude", strconv.FormatFloat(*query.Latitude, 'g', -1, 64))
		}
		if query.Longitude != nil {
			q.Set("longitude", strconv.FormatFloat(*query.Longitude, 'g', -1, 64))
		}
	}
	var out RegionsResponse
	if err := c.doJSON(ctx, "GET", "/v1/regions", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// IssueTurnCredentials — TURN credentials for a user (server-to-server)
//
// `POST /v1/turn/credentials`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: turn:issue.
func (c *Client) IssueTurnCredentials(ctx context.Context, body TurnCredentialsRequest, opts ...RequestOption) (*TurnCredentials, error) {
	var q url.Values
	var out TurnCredentials
	if err := c.doJSON(ctx, "POST", "/v1/turn/credentials", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChannels — List channels
//
// `GET /v1/channels`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: channels:read.
func (c *Client) ListChannels(ctx context.Context, query *ListChannelsQuery, opts ...RequestOption) (*ChannelList, error) {
	q := url.Values{}
	if query != nil {
		if query.Page != nil {
			q.Set("page", strconv.FormatInt(*query.Page, 10))
		}
		if query.PerPage != nil {
			q.Set("per_page", strconv.FormatInt(*query.PerPage, 10))
		}
		if query.ActiveOnly != nil {
			q.Set("active_only", strconv.FormatBool(*query.ActiveOnly))
		}
	}
	var out ChannelList
	if err := c.doJSON(ctx, "GET", "/v1/channels", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateChannel — Create a channel
//
// Fails with `409` when the application's `max_channels` quota is reached.
//
// `POST /v1/channels`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: channels:write.
func (c *Client) CreateChannel(ctx context.Context, body CreateChannelRequest, opts ...RequestOption) (*Channel, error) {
	var q url.Values
	var out Channel
	if err := c.doJSON(ctx, "POST", "/v1/channels", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetChannel — Get a channel
//
// `GET /v1/channels/{channel_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: channels:read.
func (c *Client) GetChannel(ctx context.Context, channelID string, opts ...RequestOption) (*Channel, error) {
	var q url.Values
	var out Channel
	if err := c.doJSON(ctx, "GET", "/v1/channels/"+url.PathEscape(channelID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteChannel — Delete a channel
//
// Soft-deletes the channel and disconnects its participants.
//
// `DELETE /v1/channels/{channel_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: channels:write.
func (c *Client) DeleteChannel(ctx context.Context, channelID string, opts ...RequestOption) (*DeleteChannelResponse, error) {
	var q url.Values
	var out DeleteChannelResponse
	if err := c.doJSON(ctx, "DELETE", "/v1/channels/"+url.PathEscape(channelID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateChannelConfig — Replace the channel configuration
//
// The full `ChannelConfig` is replaced (omitted fields revert to defaults). Live participants keep
// their session; new settings apply to subsequent joins.
//
// `PUT /v1/channels/{channel_id}/config`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: channels:write.
func (c *Client) UpdateChannelConfig(ctx context.Context, channelID string, body ChannelConfig, opts ...RequestOption) (*Channel, error) {
	var q url.Values
	var out Channel
	if err := c.doJSON(ctx, "PUT", "/v1/channels/"+url.PathEscape(channelID)+"/config", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetChannelParticipants — Participants of a channel
//
// `memberships` come from the database (all nodes); `live_on_this_node` adds live SFU state for
// sessions hosted by the answering node.
//
// `GET /v1/channels/{channel_id}/participants`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: channels:read.
func (c *Client) GetChannelParticipants(ctx context.Context, channelID string, opts ...RequestOption) (*ChannelParticipants, error) {
	var q url.Values
	var out ChannelParticipants
	if err := c.doJSON(ctx, "GET", "/v1/channels/"+url.PathEscape(channelID)+"/participants", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSessionStats — Live statistics of a session
//
// Node-local: the session must be hosted by the node that answers (its `media_node_id` is in `GET
// /v1/users/{user_id}`); otherwise `404`.
//
// `GET /v1/sessions/{session_id}/stats`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: channels:read.
func (c *Client) GetSessionStats(ctx context.Context, sessionID string, opts ...RequestOption) (*SessionStats, error) {
	var q url.Values
	var out SessionStats
	if err := c.doJSON(ctx, "GET", "/v1/sessions/"+url.PathEscape(sessionID)+"/stats", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchUsers — Search users
//
// `GET /v1/users`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: users:read.
func (c *Client) SearchUsers(ctx context.Context, query *SearchUsersQuery, opts ...RequestOption) ([]User, error) {
	q := url.Values{}
	if query != nil {
		if query.Q != nil {
			q.Set("q", *query.Q)
		}
		if query.Page != nil {
			q.Set("page", strconv.FormatInt(*query.Page, 10))
		}
		if query.PerPage != nil {
			q.Set("per_page", strconv.FormatInt(*query.PerPage, 10))
		}
	}
	var out []User
	err := c.doJSON(ctx, "GET", "/v1/users", q, nil, &out, opts)
	return out, err
}

// GetUser — User with active sessions
//
// `GET /v1/users/{user_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: users:read.
func (c *Client) GetUser(ctx context.Context, userID string, opts ...RequestOption) (*UserDetail, error) {
	var q url.Values
	var out UserDetail
	if err := c.doJSON(ctx, "GET", "/v1/users/"+url.PathEscape(userID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteUser — Erase a user
//
// Removes recordings, sessions, memberships, chat, blocks and the user row in one transaction,
// closes live sessions on every node and writes a tombstone so tokens issued before the deletion
// are rejected. Moderation evidence is kept unless `purge_moderation=true`.
//
// `DELETE /v1/users/{user_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: users:erase.
func (c *Client) DeleteUser(ctx context.Context, userID string, query *DeleteUserQuery, opts ...RequestOption) (*UserDeletion, error) {
	q := url.Values{}
	if query != nil {
		if query.PurgeModeration != nil {
			q.Set("purge_moderation", strconv.FormatBool(*query.PurgeModeration))
		}
	}
	var out UserDeletion
	if err := c.doJSON(ctx, "DELETE", "/v1/users/"+url.PathEscape(userID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ExportUser — Export everything stored about a user
//
// `GET /v1/users/{user_id}/export`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: users:export.
func (c *Client) ExportUser(ctx context.Context, userID string, opts ...RequestOption) (*UserExport, error) {
	var q url.Values
	var out UserExport
	if err := c.doJSON(ctx, "GET", "/v1/users/"+url.PathEscape(userID)+"/export", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// UnbanUser — Revoke all active bans of a user
//
// `POST /v1/users/{user_id}/unban`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) UnbanUser(ctx context.Context, userID string, body *UnbanRequest, opts ...RequestOption) (*UnbanUserResponse, error) {
	var q url.Values
	var bodyArg any
	if body != nil {
		bodyArg = body
	}
	var out UnbanUserResponse
	if err := c.doJSON(ctx, "POST", "/v1/users/"+url.PathEscape(userID)+"/unban", q, bodyArg, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListUserBlocks — Users this user has blocked
//
// `GET /v1/users/{user_id}/blocks`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: users:read.
func (c *Client) ListUserBlocks(ctx context.Context, userID string, opts ...RequestOption) (*UserBlocks, error) {
	var q url.Values
	var out UserBlocks
	if err := c.doJSON(ctx, "GET", "/v1/users/"+url.PathEscape(userID)+"/blocks", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AddUserBlock — Block another user
//
// Persistent, mutual: neither side hears or reads the other, on every node and after reconnects.
//
// `POST /v1/users/{user_id}/blocks`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: users:write.
func (c *Client) AddUserBlock(ctx context.Context, userID string, body BlockRequest, opts ...RequestOption) (*BlockResult, error) {
	var q url.Values
	var out BlockResult
	if err := c.doJSON(ctx, "POST", "/v1/users/"+url.PathEscape(userID)+"/blocks", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveUserBlock — Remove a block
//
// `DELETE /v1/users/{user_id}/blocks/{blocked_user_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: users:write.
func (c *Client) RemoveUserBlock(ctx context.Context, userID string, blockedUserID string, opts ...RequestOption) (*BlockResult, error) {
	var q url.Values
	var out BlockResult
	if err := c.doJSON(ctx, "DELETE", "/v1/users/"+url.PathEscape(userID)+"/blocks/"+url.PathEscape(blockedUserID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChannelMessages — Channel message history
//
// History endpoints require `chat.persist = true` on the deployment (otherwise `404`). Pages are
// newest first; follow `next_before` to older messages and `next_after` to newer ones (absent when
// there is nothing more in that direction).
//
// `GET /v1/channels/{channel_id}/messages`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:read.
func (c *Client) ListChannelMessages(ctx context.Context, channelID string, query *ListChannelMessagesQuery, opts ...RequestOption) (*ChatHistoryPage, error) {
	q := url.Values{}
	if query != nil {
		if query.Before != nil {
			q.Set("before", *query.Before)
		}
		if query.After != nil {
			q.Set("after", *query.After)
		}
		if query.Limit != nil {
			q.Set("limit", strconv.FormatInt(*query.Limit, 10))
		}
	}
	var out ChatHistoryPage
	if err := c.doJSON(ctx, "GET", "/v1/channels/"+url.PathEscape(channelID)+"/messages", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// SendChannelMessage — Send a system message to a channel
//
// Delivered live to every participant as `ChatMessageReceived` from the system user.
//
// `POST /v1/channels/{channel_id}/messages`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:write.
func (c *Client) SendChannelMessage(ctx context.Context, channelID string, body SystemMessageRequest, opts ...RequestOption) (*ChatMessage, error) {
	var q url.Values
	var out ChatMessage
	if err := c.doJSON(ctx, "POST", "/v1/channels/"+url.PathEscape(channelID)+"/messages", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListUserMessages — Directed message history of a user
//
// History endpoints require `chat.persist = true` on the deployment (otherwise `404`). Pages are
// newest first; follow `next_before` to older messages and `next_after` to newer ones (absent when
// there is nothing more in that direction).
//
// `GET /v1/users/{user_id}/messages`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:read.
func (c *Client) ListUserMessages(ctx context.Context, userID string, query *ListUserMessagesQuery, opts ...RequestOption) (*ChatHistoryPage, error) {
	q := url.Values{}
	if query != nil {
		if query.Before != nil {
			q.Set("before", *query.Before)
		}
		if query.After != nil {
			q.Set("after", *query.After)
		}
		if query.Limit != nil {
			q.Set("limit", strconv.FormatInt(*query.Limit, 10))
		}
		if query.Peer != nil {
			q.Set("peer", *query.Peer)
		}
	}
	var out ChatHistoryPage
	if err := c.doJSON(ctx, "GET", "/v1/users/"+url.PathEscape(userID)+"/messages", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// SendUserMessage — Send a system message to one online user
//
// The user must currently have a live session (no offline delivery).
//
// `POST /v1/users/{user_id}/messages`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:write.
func (c *Client) SendUserMessage(ctx context.Context, userID string, body SystemMessageRequest, opts ...RequestOption) (*ChatMessage, error) {
	var q url.Values
	var out ChatMessage
	if err := c.doJSON(ctx, "POST", "/v1/users/"+url.PathEscape(userID)+"/messages", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AnnounceInChannel — Speak an announcement into a channel
//
// Synthesises `text` with the configured `[tts]` provider and injects it as a system voice
// participant; returns as soon as the request is queued (`501` if no provider is configured).
//
// `POST /v1/channels/{channel_id}/tts`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: tts:write.
func (c *Client) AnnounceInChannel(ctx context.Context, channelID string, body AnnounceRequest, opts ...RequestOption) (*AnnounceInChannelResponse, error) {
	var q url.Values
	var out AnnounceInChannelResponse
	if err := c.doJSON(ctx, "POST", "/v1/channels/"+url.PathEscape(channelID)+"/tts", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// TTSVoices — Available TTS voices and limits
//
// `GET /v1/tts/voices`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: channels:read.
func (c *Client) TTSVoices(ctx context.Context, opts ...RequestOption) (*TtsVoicesResponse, error) {
	var q url.Values
	var out TtsVoicesResponse
	if err := c.doJSON(ctx, "GET", "/v1/tts/voices", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// BanUser — Ban a user, device or IP
//
// Live sessions of the user are closed on every node.
//
// `POST /v1/moderation/ban`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) BanUser(ctx context.Context, body BanRequest, opts ...RequestOption) (*Ban, error) {
	var q url.Values
	var out Ban
	if err := c.doJSON(ctx, "POST", "/v1/moderation/ban", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBans — List bans
//
// `GET /v1/moderation/bans`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:read.
func (c *Client) ListBans(ctx context.Context, query *ListBansQuery, opts ...RequestOption) ([]Ban, error) {
	q := url.Values{}
	if query != nil {
		if query.UserID != nil {
			q.Set("user_id", *query.UserID)
		}
		if query.Page != nil {
			q.Set("page", strconv.FormatInt(*query.Page, 10))
		}
		if query.PerPage != nil {
			q.Set("per_page", strconv.FormatInt(*query.PerPage, 10))
		}
	}
	var out []Ban
	err := c.doJSON(ctx, "GET", "/v1/moderation/bans", q, nil, &out, opts)
	return out, err
}

// RevokeBan — Revoke one ban
//
// `POST /v1/moderation/bans/{ban_id}/revoke`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) RevokeBan(ctx context.Context, banID string, body *UnbanRequest, opts ...RequestOption) (*RevokeBanResponse, error) {
	var q url.Values
	var bodyArg any
	if body != nil {
		bodyArg = body
	}
	var out RevokeBanResponse
	if err := c.doJSON(ctx, "POST", "/v1/moderation/bans/"+url.PathEscape(banID)+"/revoke", q, bodyArg, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ServerMute — Server-mute or unmute a participant
//
// `POST /v1/moderation/mute`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) ServerMute(ctx context.Context, body ServerMuteRequest, opts ...RequestOption) (*ServerMuteResponse, error) {
	var q url.Values
	var out ServerMuteResponse
	if err := c.doJSON(ctx, "POST", "/v1/moderation/mute", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// MuteAll — Server-mute or unmute everyone in a channel
//
// `POST /v1/moderation/mute-all`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) MuteAll(ctx context.Context, body MuteAllRequest, opts ...RequestOption) (*BulkModerationResult, error) {
	var q url.Values
	var out BulkModerationResult
	if err := c.doJSON(ctx, "POST", "/v1/moderation/mute-all", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// SetPriority — Promote or demote a priority speaker
//
// Sets the priority-speaker flag on the user's open membership in the channel and notifies every
// member (`PriorityChanged`). While a priority speaker talks, non-priority streams are attenuated
// per `ChannelConfig.ducking`. `404` when the user is not currently a member.
//
// `POST /v1/moderation/priority`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) SetPriority(ctx context.Context, body SetPriorityRequest, opts ...RequestOption) (*SetPriorityResponse, error) {
	var q url.Values
	var out SetPriorityResponse
	if err := c.doJSON(ctx, "POST", "/v1/moderation/priority", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// KickUser — Kick a participant from a channel
//
// `POST /v1/moderation/kick`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) KickUser(ctx context.Context, body KickRequest, opts ...RequestOption) (*KickUserResponse, error) {
	var q url.Values
	var out KickUserResponse
	if err := c.doJSON(ctx, "POST", "/v1/moderation/kick", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// KickAll — Kick everyone from a channel
//
// `POST /v1/moderation/kick-all`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) KickAll(ctx context.Context, body KickAllRequest, opts ...RequestOption) (*BulkModerationResult, error) {
	var q url.Values
	var out BulkModerationResult
	if err := c.doJSON(ctx, "POST", "/v1/moderation/kick-all", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ReportUser — File a report on behalf of a user
//
// `POST /v1/moderation/report`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) ReportUser(ctx context.Context, body ReportRequest, opts ...RequestOption) (*ModerationEvent, error) {
	var q url.Values
	var out ModerationEvent
	if err := c.doJSON(ctx, "POST", "/v1/moderation/report", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListModerationEvents — List moderation events (reports, bans, kicks…)
//
// `GET /v1/moderation/events`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:read.
func (c *Client) ListModerationEvents(ctx context.Context, query *ListModerationEventsQuery, opts ...RequestOption) ([]ModerationEvent, error) {
	q := url.Values{}
	if query != nil {
		if query.Status != nil {
			q.Set("status", *query.Status)
		}
		if query.Page != nil {
			q.Set("page", strconv.FormatInt(*query.Page, 10))
		}
		if query.PerPage != nil {
			q.Set("per_page", strconv.FormatInt(*query.PerPage, 10))
		}
	}
	var out []ModerationEvent
	err := c.doJSON(ctx, "GET", "/v1/moderation/events", q, nil, &out, opts)
	return out, err
}

// GetModerationEvent — Get a moderation event
//
// `GET /v1/moderation/events/{event_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:read.
func (c *Client) GetModerationEvent(ctx context.Context, eventID string, opts ...RequestOption) (*ModerationEvent, error) {
	var q url.Values
	var out ModerationEvent
	if err := c.doJSON(ctx, "GET", "/v1/moderation/events/"+url.PathEscape(eventID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ResolveModerationEvent — Resolve a moderation event
//
// `POST /v1/moderation/events/{event_id}/resolve`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:write.
func (c *Client) ResolveModerationEvent(ctx context.Context, eventID string, body ResolveModerationEventRequest, opts ...RequestOption) (*ResolveModerationEventResponse, error) {
	var q url.Values
	var out ResolveModerationEventResponse
	if err := c.doJSON(ctx, "POST", "/v1/moderation/events/"+url.PathEscape(eventID)+"/resolve", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSafetyIncidents — List content-safety incidents
//
// Incidents raised by the `[safety]` pipeline. They are moderation events with `event_type`
// `safety.voice` or `safety.text` (so `POST /v1/moderation/events/{event_id}/resolve` closes
// them); `evidence` holds the score, categories, flagged text, classifier and lexicon verdicts,
// context messages and the evidence-clip metadata. Newest first.
//
// `GET /v1/safety/incidents`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:read.
func (c *Client) ListSafetyIncidents(ctx context.Context, query *ListSafetyIncidentsQuery, opts ...RequestOption) ([]ModerationEvent, error) {
	q := url.Values{}
	if query != nil {
		if query.UserID != nil {
			q.Set("user_id", *query.UserID)
		}
		if query.Source != nil {
			q.Set("source", string(*query.Source))
		}
		if query.Status != nil {
			q.Set("status", *query.Status)
		}
		if query.Page != nil {
			q.Set("page", strconv.FormatInt(*query.Page, 10))
		}
		if query.PerPage != nil {
			q.Set("per_page", strconv.FormatInt(*query.PerPage, 10))
		}
	}
	var out []ModerationEvent
	err := c.doJSON(ctx, "GET", "/v1/safety/incidents", q, nil, &out, opts)
	return out, err
}

// GetSafetyIncident — Get a content-safety incident
//
// The incident with its context messages and, for voice incidents with a stored clip, the
// recording metadata and the path that streams it (`recordings:read`).
//
// `GET /v1/safety/incidents/{incident_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:read.
func (c *Client) GetSafetyIncident(ctx context.Context, incidentID string, opts ...RequestOption) (*SafetyIncident, error) {
	var q url.Values
	var out SafetyIncident
	if err := c.doJSON(ctx, "GET", "/v1/safety/incidents/"+url.PathEscape(incidentID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ExportSafetyIncident — Export an incident with its evidence
//
// Self-contained JSON bundle for hand-off to a trust & safety team: the incident, the surrounding
// chat messages and — when a clip exists **and the key also holds `recordings:read`** — the
// decrypted Ogg/Opus audio inline as `audio.content_base64`. Reading the clip is written to the
// audit log as `recording.accessed`. Without `recordings:read` the bundle is returned without the
// audio bytes.
//
// `GET /v1/safety/incidents/{incident_id}/export`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:read.
func (c *Client) ExportSafetyIncident(ctx context.Context, incidentID string, opts ...RequestOption) (*SafetyIncidentExport, error) {
	var q url.Values
	var out SafetyIncidentExport
	if err := c.doJSON(ctx, "GET", "/v1/safety/incidents/"+url.PathEscape(incidentID)+"/export", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSafetyUserRisk — Current risk of a user
//
// Decayed sum of the user's recent incident scores (`[safety].risk_half_life_secs`), the same
// value that drives automatic mute/kick triggers and `safety.risk_changed` events. Computed from
// stored incidents, identical on every node.
//
// `GET /v1/safety/users/{user_id}/risk`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: moderation:read.
func (c *Client) GetSafetyUserRisk(ctx context.Context, userID string, opts ...RequestOption) (*SafetyRisk, error) {
	var q url.Values
	var out SafetyRisk
	if err := c.doJSON(ctx, "GET", "/v1/safety/users/"+url.PathEscape(userID)+"/risk", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAnalytics — Current counters, range totals and the application time series
//
// CCU (`peak_sessions`), session and participant minutes, unique users, active channels and
// metered counters per bucket. Lifecycle metrics (CCU, minutes, unique users) are derived from
// session and membership intervals by a fleet-wide aggregator that runs every
// `usage.aggregate_interval_secs`; metered counters (media bytes, chat, TTS, STT) are flushed by
// every node every `usage.flush_interval_secs`. Buckets before `range.finalized_through` are
// final; the current one is still accruing. Clock-time is UTC; buckets are aligned to epoch
// multiples of the step.
//
// `GET /v1/analytics`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: analytics:read.
func (c *Client) GetAnalytics(ctx context.Context, query *GetAnalyticsQuery, opts ...RequestOption) (*AppUsage, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
		if query.Step != nil {
			q.Set("step", strconv.FormatInt(*query.Step, 10))
		}
	}
	var out AppUsage
	if err := c.doJSON(ctx, "GET", "/v1/analytics", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetQuota — Limits of the application and how much of them is used
//
// `max_concurrent_sessions` and `monthly_participant_minutes` are set by the operator (`PATCH
// /v1/apps/{app_id}`); `0` means unlimited. Consumption is fleet-wide.
//
// `GET /v1/analytics/quota`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: analytics:read.
func (c *Client) GetQuota(ctx context.Context, opts ...RequestOption) (*QuotaState, error) {
	var q url.Values
	var out QuotaState
	if err := c.doJSON(ctx, "GET", "/v1/analytics/quota", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSessionQuality — Sessions with the worst MOS over a range
//
// Sessions (live and closed) that connected in the range, ordered by mean MOS ascending, each with
// its persisted `QualitySummary`. Live sessions show the summary as of their last checkpoint
// (`quality.persist_interval_secs`); `GET /v1/sessions/{session_id}/stats` has the live value. Use
// this to find who had a bad call instead of high-cardinality metrics — Prometheus only carries
// fleet-wide distributions.
//
// `GET /v1/analytics/sessions`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: analytics:read.
func (c *Client) ListSessionQuality(ctx context.Context, query *ListSessionQualityQuery, opts ...RequestOption) (*SessionQualityList, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
		if query.Limit != nil {
			q.Set("limit", strconv.FormatInt(*query.Limit, 10))
		}
		if query.MinSamples != nil {
			q.Set("min_samples", strconv.FormatInt(*query.MinSamples, 10))
		}
	}
	var out SessionQualityList
	if err := c.doJSON(ctx, "GET", "/v1/analytics/sessions", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChannelUsage — Per-channel totals over a range, busiest first
//
// Channels that had any usage in the range (including deleted ones — usage outlives the channel),
// ordered by participant minutes.
//
// `GET /v1/analytics/channels`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: analytics:read.
func (c *Client) ListChannelUsage(ctx context.Context, query *ListChannelUsageQuery, opts ...RequestOption) (*ChannelUsageList, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
		if query.Limit != nil {
			q.Set("limit", strconv.FormatInt(*query.Limit, 10))
		}
	}
	var out ChannelUsageList
	if err := c.doJSON(ctx, "GET", "/v1/analytics/channels", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetChannelUsage — Hourly series of one channel
//
// Peak participants, participant minutes, joins, unique users and metered counters per hour. A
// channel that neither exists in the application nor has usage there is `404`.
//
// `GET /v1/analytics/channels/{channel_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: analytics:read.
func (c *Client) GetChannelUsage(ctx context.Context, channelID string, query *GetChannelUsageQuery, opts ...RequestOption) (*ChannelUsage, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
	}
	var out ChannelUsage
	if err := c.doJSON(ctx, "GET", "/v1/analytics/channels/"+url.PathEscape(channelID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ExportUsage — Raw usage buckets for billing or BI (JSON or CSV)
//
// Every bucket of the application in the range: 5-minute application rows (`scope=app`, default)
// or hourly per-channel rows (`scope=channels`). At most 200 000 rows per call — `truncated`
// (JSON) / `X-Aurix-Truncated` (CSV) signals a cut; page by narrowing `from`/`to`. Default range:
// the last 30 days.
//
// `GET /v1/analytics/export`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: analytics:read.
//
// When the server answers with text/csv (non-JSON `format`) this call fails; use the `ExportUsageRaw` instead.
func (c *Client) ExportUsage(ctx context.Context, query *ExportUsageQuery, opts ...RequestOption) (*UsageExport, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
		if query.Scope != nil {
			q.Set("scope", string(*query.Scope))
		}
		if query.Format != nil {
			q.Set("format", string(*query.Format))
		}
	}
	var out UsageExport
	if err := c.doJSON(ctx, "GET", "/v1/analytics/export", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ExportUsageRaw — Raw usage buckets for billing or BI (JSON or CSV)
//
// Every bucket of the application in the range: 5-minute application rows (`scope=app`, default)
// or hourly per-channel rows (`scope=channels`). At most 200 000 rows per call — `truncated`
// (JSON) / `X-Aurix-Truncated` (CSV) signals a cut; page by narrowing `from`/`to`. Default range:
// the last 30 days.
//
// `GET /v1/analytics/export`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: analytics:read.
//
// Returns the raw body (application/json, text/csv).
func (c *Client) ExportUsageRaw(ctx context.Context, query *ExportUsageQuery, opts ...RequestOption) (*RawResponse, error) {
	q := url.Values{}
	if query != nil {
		if query.From != nil {
			q.Set("from", *query.From)
		}
		if query.To != nil {
			q.Set("to", *query.To)
		}
		if query.Scope != nil {
			q.Set("scope", string(*query.Scope))
		}
		if query.Format != nil {
			q.Set("format", string(*query.Format))
		}
	}
	return c.doRaw(ctx, "GET", "/v1/analytics/export", q, nil, opts, "*/*")
}

// ListAPIKeys — List API keys (secrets redacted)
//
// `GET /v1/api-keys`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: keys:manage.
func (c *Client) ListAPIKeys(ctx context.Context, opts ...RequestOption) ([]ApiKey, error) {
	var q url.Values
	var out []ApiKey
	err := c.doJSON(ctx, "GET", "/v1/api-keys", q, nil, &out, opts)
	return out, err
}

// CreateAPIKey — Create an API key
//
// A key can only grant permissions it holds itself. The raw key is returned once.
//
// `POST /v1/api-keys`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: keys:manage.
func (c *Client) CreateAPIKey(ctx context.Context, body CreateApiKeyRequest, opts ...RequestOption) (*CreatedApiKey, error) {
	var q url.Values
	var out CreatedApiKey
	if err := c.doJSON(ctx, "POST", "/v1/api-keys", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateAPIKey — Change an API key's request budget
//
// Takes effect on the next request on every node (buckets are shared through Redis).
//
// `PATCH /v1/api-keys/{key_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: keys:manage.
func (c *Client) UpdateAPIKey(ctx context.Context, keyID string, body UpdateApiKeyRequest, opts ...RequestOption) (*ApiKey, error) {
	var q url.Values
	var out ApiKey
	if err := c.doJSON(ctx, "PATCH", "/v1/api-keys/"+url.PathEscape(keyID), q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// RevokeAPIKey — Revoke an API key
//
// `DELETE /v1/api-keys/{key_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: keys:manage.
func (c *Client) RevokeAPIKey(ctx context.Context, keyID string, opts ...RequestOption) (*RevokeApiKeyResponse, error) {
	var q url.Values
	var out RevokeApiKeyResponse
	if err := c.doJSON(ctx, "DELETE", "/v1/api-keys/"+url.PathEscape(keyID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAuditLog — Audit log of this application
//
// Hash-chained; every privileged action (keys, bans, kicks, recording access, …) is recorded.
//
// `GET /v1/audit-log`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: audit:read.
func (c *Client) ListAuditLog(ctx context.Context, query *ListAuditLogQuery, opts ...RequestOption) ([]AuditLogEntry, error) {
	q := url.Values{}
	if query != nil {
		if query.Page != nil {
			q.Set("page", strconv.FormatInt(*query.Page, 10))
		}
		if query.PerPage != nil {
			q.Set("per_page", strconv.FormatInt(*query.PerPage, 10))
		}
	}
	var out []AuditLogEntry
	err := c.doJSON(ctx, "GET", "/v1/audit-log", q, nil, &out, opts)
	return out, err
}

// ListRecordings — List recordings
//
// `GET /v1/recordings`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:read.
func (c *Client) ListRecordings(ctx context.Context, query *ListRecordingsQuery, opts ...RequestOption) ([]Recording, error) {
	q := url.Values{}
	if query != nil {
		if query.ChannelID != nil {
			q.Set("channel_id", *query.ChannelID)
		}
		if query.Page != nil {
			q.Set("page", strconv.FormatInt(*query.Page, 10))
		}
		if query.PerPage != nil {
			q.Set("per_page", strconv.FormatInt(*query.PerPage, 10))
		}
	}
	var out []Recording
	err := c.doJSON(ctx, "GET", "/v1/recordings", q, nil, &out, opts)
	return out, err
}

// StartRecording — Start recording a participant
//
// Requires `recording.enabled` on the node and the participant to be live on it. With
// `recording.require_consent` audio is written only after the participant accepts the
// `RecordingNotification`.
//
// `POST /v1/recordings/start`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:write.
func (c *Client) StartRecording(ctx context.Context, body StartRecordingRequest, opts ...RequestOption) (*Recording, error) {
	var q url.Values
	var out Recording
	if err := c.doJSON(ctx, "POST", "/v1/recordings/start", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRecording — Recording metadata, download URL and consent state
//
// `GET /v1/recordings/{recording_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:read.
func (c *Client) GetRecording(ctx context.Context, recordingID string, opts ...RequestOption) (*GetRecordingResponse, error) {
	var q url.Values
	var out GetRecordingResponse
	if err := c.doJSON(ctx, "GET", "/v1/recordings/"+url.PathEscape(recordingID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteRecording — Delete a recording and its file
//
// `DELETE /v1/recordings/{recording_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:write.
func (c *Client) DeleteRecording(ctx context.Context, recordingID string, opts ...RequestOption) (*DeleteRecordingResponse, error) {
	var q url.Values
	var out DeleteRecordingResponse
	if err := c.doJSON(ctx, "DELETE", "/v1/recordings/"+url.PathEscape(recordingID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// DownloadRecordingRaw — Download the recording file
//
// Decrypted on the fly when recording encryption is enabled. Access is written to the audit log.
// Participant tracks and Opus mixdowns are Ogg/Opus, WAV mixdowns are 16-bit PCM. 409 while the
// recording is still `recording`/`processing` or has `failed`.
//
// `GET /v1/recordings/{recording_id}/download`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:read.
//
// Returns the raw body (audio/ogg, audio/wav).
func (c *Client) DownloadRecordingRaw(ctx context.Context, recordingID string, opts ...RequestOption) (*RawResponse, error) {
	var q url.Values
	return c.doRaw(ctx, "GET", "/v1/recordings/"+url.PathEscape(recordingID)+"/download", q, nil, opts, "*/*")
}

// StopRecording — Stop a running recording
//
// `POST /v1/recordings/{recording_id}/stop`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:write.
func (c *Client) StopRecording(ctx context.Context, recordingID string, opts ...RequestOption) (*Recording, error) {
	var q url.Values
	var out Recording
	if err := c.doJSON(ctx, "POST", "/v1/recordings/"+url.PathEscape(recordingID)+"/stop", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListStreams — Live streams of this application on this node
//
// Streams of the tenant across the whole fleet: this node's live status plus the directory entries
// of streams owned by other nodes.
//
// `GET /v1/audio/streams`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: audio_streams:read.
func (c *Client) ListStreams(ctx context.Context, opts ...RequestOption) (*ListStreamsResponse, error) {
	var q url.Values
	var out ListStreamsResponse
	if err := c.doJSON(ctx, "GET", "/v1/audio/streams", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChannelStreams — Live streams of a channel on this node
//
// Streams of the tenant across the whole fleet: this node's live status plus the directory entries
// of streams owned by other nodes.
//
// `GET /v1/channels/{channel_id}/audio/streams`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: audio_streams:read.
func (c *Client) ListChannelStreams(ctx context.Context, channelID string, opts ...RequestOption) (*ListChannelStreamsResponse, error) {
	var q url.Values
	var out ListChannelStreamsResponse
	if err := c.doJSON(ctx, "GET", "/v1/channels/"+url.PathEscape(channelID)+"/audio/streams", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateStream — Start a push stream
//
// Aurix connects to your WebSocket endpoint and pushes per-participant Opus or PCM frames (36-byte
// binary header) plus JSON control frames, or one server-side mix (`mix: true`). Any node of the
// fleet can create the stream: the node pins the channel so the cascade forwards every
// participant's audio to it, and publishes the stream to the fleet directory.
//
// `POST /v1/channels/{channel_id}/audio/streams`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: audio_streams:write.
func (c *Client) CreateStream(ctx context.Context, channelID string, body CreateStreamRequest, opts ...RequestOption) (*LiveStream, error) {
	var q url.Values
	var out LiveStream
	if err := c.doJSON(ctx, "POST", "/v1/channels/"+url.PathEscape(channelID)+"/audio/streams", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStream — Get a live stream
//
// `GET /v1/channels/{channel_id}/audio/streams/{stream_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: audio_streams:read.
func (c *Client) GetStream(ctx context.Context, channelID string, streamID string, opts ...RequestOption) (*LiveStream, error) {
	var q url.Values
	var out LiveStream
	if err := c.doJSON(ctx, "GET", "/v1/channels/"+url.PathEscape(channelID)+"/audio/streams/"+url.PathEscape(streamID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteStream — Stop a live stream
//
// A stream owned by this node is closed synchronously (`200`, final counters). A stream owned by
// another node is asked to stop through the control plane (`202`, its last published status); it
// disappears from the directory once that node has closed it.
//
// `DELETE /v1/channels/{channel_id}/audio/streams/{stream_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: audio_streams:write.
func (c *Client) DeleteStream(ctx context.Context, channelID string, streamID string, opts ...RequestOption) (*LiveStream, error) {
	var q url.Values
	var out LiveStream
	if err := c.doJSON(ctx, "DELETE", "/v1/channels/"+url.PathEscape(channelID)+"/audio/streams/"+url.PathEscape(streamID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListWebhooks — List webhook subscriptions
//
// `GET /v1/webhooks`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:read.
func (c *Client) ListWebhooks(ctx context.Context, opts ...RequestOption) (*ListWebhooksResponse, error) {
	var q url.Values
	var out ListWebhooksResponse
	if err := c.doJSON(ctx, "GET", "/v1/webhooks", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateWebhook — Create a webhook subscription
//
// The response includes `secret` (once). Deliveries are `POST`s with the `EventEnvelope` body and
// `X-Aurix-Signature: t=<unix>,v1=hex(HMAC-SHA256(secret, "<t>.<body>"))`; failures retry from 5 s
// up to 2 h.
//
// `POST /v1/webhooks`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:write.
func (c *Client) CreateWebhook(ctx context.Context, body CreateWebhookRequest, opts ...RequestOption) (*Webhook, error) {
	var q url.Values
	var out Webhook
	if err := c.doJSON(ctx, "POST", "/v1/webhooks", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListEventTypes — Event types and the signature scheme
//
// `webhook` lists what a subscription may ask for, `stream` what the SSE stream can deliver (adds
// the high-frequency typing/speaking/energy events).
//
// `GET /v1/webhooks/events`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:read, events:read (either).
func (c *Client) ListEventTypes(ctx context.Context, opts ...RequestOption) (*EventTypes, error) {
	var q url.Values
	var out EventTypes
	if err := c.doJSON(ctx, "GET", "/v1/webhooks/events", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetWebhook — Get a webhook
//
// `GET /v1/webhooks/{webhook_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:read.
func (c *Client) GetWebhook(ctx context.Context, webhookID string, opts ...RequestOption) (*Webhook, error) {
	var q url.Values
	var out Webhook
	if err := c.doJSON(ctx, "GET", "/v1/webhooks/"+url.PathEscape(webhookID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateWebhook — Update a webhook
//
// `PATCH /v1/webhooks/{webhook_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:write.
func (c *Client) UpdateWebhook(ctx context.Context, webhookID string, body UpdateWebhookRequest, opts ...RequestOption) (*Webhook, error) {
	var q url.Values
	var out Webhook
	if err := c.doJSON(ctx, "PATCH", "/v1/webhooks/"+url.PathEscape(webhookID), q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteWebhook — Delete a webhook
//
// `DELETE /v1/webhooks/{webhook_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:write.
func (c *Client) DeleteWebhook(ctx context.Context, webhookID string, opts ...RequestOption) error {
	var q url.Values
	return c.doJSON(ctx, "DELETE", "/v1/webhooks/"+url.PathEscape(webhookID), q, nil, nil, opts)
}

// RotateWebhookSecret — Rotate the signing secret
//
// The new `secret` is returned once; the old one stops working immediately.
//
// `POST /v1/webhooks/{webhook_id}/rotate-secret`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:write.
func (c *Client) RotateWebhookSecret(ctx context.Context, webhookID string, opts ...RequestOption) (*Webhook, error) {
	var q url.Values
	var out Webhook
	if err := c.doJSON(ctx, "POST", "/v1/webhooks/"+url.PathEscape(webhookID)+"/rotate-secret", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// TestWebhook — Enqueue a `webhook.test` delivery
//
// `POST /v1/webhooks/{webhook_id}/test`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:write.
func (c *Client) TestWebhook(ctx context.Context, webhookID string, opts ...RequestOption) (*TestWebhookResponse, error) {
	var q url.Values
	var out TestWebhookResponse
	if err := c.doJSON(ctx, "POST", "/v1/webhooks/"+url.PathEscape(webhookID)+"/test", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ResyncWebhook — Enqueue a `webhook.resync` delivery with the current channel/participant snapshot
//
// `POST /v1/webhooks/{webhook_id}/resync`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:write.
func (c *Client) ResyncWebhook(ctx context.Context, webhookID string, opts ...RequestOption) (*ResyncWebhookResponse, error) {
	var q url.Values
	var out ResyncWebhookResponse
	if err := c.doJSON(ctx, "POST", "/v1/webhooks/"+url.PathEscape(webhookID)+"/resync", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListWebhookDeliveries — Delivery log of a webhook
//
// `GET /v1/webhooks/{webhook_id}/deliveries`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:read.
func (c *Client) ListWebhookDeliveries(ctx context.Context, webhookID string, query *ListWebhookDeliveriesQuery, opts ...RequestOption) (*ListWebhookDeliveriesResponse, error) {
	q := url.Values{}
	if query != nil {
		if query.Status != nil {
			q.Set("status", *query.Status)
		}
		if query.Limit != nil {
			q.Set("limit", strconv.FormatInt(*query.Limit, 10))
		}
		if query.Offset != nil {
			q.Set("offset", strconv.FormatInt(*query.Offset, 10))
		}
	}
	var out ListWebhookDeliveriesResponse
	if err := c.doJSON(ctx, "GET", "/v1/webhooks/"+url.PathEscape(webhookID)+"/deliveries", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetWebhookDelivery — Get a delivery
//
// `GET /v1/webhooks/{webhook_id}/deliveries/{delivery_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:read.
func (c *Client) GetWebhookDelivery(ctx context.Context, webhookID string, deliveryID string, opts ...RequestOption) (*WebhookDelivery, error) {
	var q url.Values
	var out WebhookDelivery
	if err := c.doJSON(ctx, "GET", "/v1/webhooks/"+url.PathEscape(webhookID)+"/deliveries/"+url.PathEscape(deliveryID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetryWebhookDelivery — Retry a delivery now
//
// `POST /v1/webhooks/{webhook_id}/deliveries/{delivery_id}/retry`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: webhooks:write.
func (c *Client) RetryWebhookDelivery(ctx context.Context, webhookID string, deliveryID string, opts ...RequestOption) (*RetryWebhookDeliveryResponse, error) {
	var q url.Values
	var out RetryWebhookDeliveryResponse
	if err := c.doJSON(ctx, "POST", "/v1/webhooks/"+url.PathEscape(webhookID)+"/deliveries/"+url.PathEscape(deliveryID)+"/retry", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// EventSnapshot — Current channels and participants
//
// Use after `lagged` or on (re)connect to rebuild local state.
//
// `GET /v1/events/snapshot`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: events:read.
func (c *Client) EventSnapshot(ctx context.Context, opts ...RequestOption) (*EventSnapshot, error) {
	var q url.Values
	var out EventSnapshot
	if err := c.doJSON(ctx, "GET", "/v1/events/snapshot", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// MyTurnCredentials — TURN credentials for the calling player
//
// `GET /v1/me/turn-credentials`
// Auth: PlayerToken.
func (c *Client) MyTurnCredentials(ctx context.Context, opts ...RequestOption) (*TurnCredentials, error) {
	var q url.Values
	var out TurnCredentials
	if err := c.doJSON(ctx, "GET", "/v1/me/turn-credentials", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// MyRegions — Region discovery for the calling player
//
// Same list as `GET /v1/regions`, for the SDKs: they probe every `probe_url`, connect to the node
// with the lowest RTT and fall back to the server's order when probing is impossible. Requires
// only a session token.
//
// `GET /v1/me/regions`
// Auth: PlayerToken.
func (c *Client) MyRegions(ctx context.Context, query *MyRegionsQuery, opts ...RequestOption) (*RegionsResponse, error) {
	q := url.Values{}
	if query != nil {
		if query.Region != nil {
			q.Set("region", string(*query.Region))
		}
		if query.Latitude != nil {
			q.Set("latitude", strconv.FormatFloat(*query.Latitude, 'g', -1, 64))
		}
		if query.Longitude != nil {
			q.Set("longitude", strconv.FormatFloat(*query.Longitude, 'g', -1, 64))
		}
	}
	var out RegionsResponse
	if err := c.doJSON(ctx, "GET", "/v1/me/regions", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ReportUserSelf — Report another user
//
// The reporter is the authenticated player.
//
// `POST /v1/me/reports`
// Auth: PlayerToken.
func (c *Client) ReportUserSelf(ctx context.Context, body SelfReportRequest, opts ...RequestOption) (*ModerationEvent, error) {
	var q url.Values
	var out ModerationEvent
	if err := c.doJSON(ctx, "POST", "/v1/me/reports", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// RecordingConsent — Answer a recording consent request over REST
//
// Equivalent to the WebSocket `RecordingConsentResponse`; only the recorded participant may
// answer.
//
// `POST /v1/me/recordings/{recording_id}/consent`
// Auth: PlayerToken.
func (c *Client) RecordingConsent(ctx context.Context, recordingID string, body RecordingConsentRequest, opts ...RequestOption) (*RecordingConsentResponse, error) {
	var q url.Values
	var out RecordingConsentResponse
	if err := c.doJSON(ctx, "POST", "/v1/me/recordings/"+url.PathEscape(recordingID)+"/consent", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// WebrtcOffer — WebRTC signalling: SDP offer → answer
//
// Alternative to the WebSocket `WebRtcOffer` message. The session must have been opened over the
// WebSocket by the same player; the SDP is limited to 64 KiB.
//
// `POST /v1/webrtc/offer`
// Auth: PlayerToken.
func (c *Client) WebrtcOffer(ctx context.Context, body WebRtcOfferRequest, opts ...RequestOption) (*WebRtcAnswer, error) {
	var q url.Values
	var out WebRtcAnswer
	if err := c.doJSON(ctx, "POST", "/v1/webrtc/offer", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// MixdownRecordings — Render a channel mixdown from participant tracks
//
// Combines finished per-participant tracks of one channel (aligned on `audio_started_at`, summed
// with soft clipping) into a single Ogg/Opus or WAV file. Returns the new recording with `kind =
// mixdown` and `status = processing`; it becomes `ready` asynchronously — poll `GET
// /v1/recordings/{id}` or subscribe to `recording.processed`. The job runs on the node that
// accepted the request, which must be able to read every source (its own files or object storage);
// otherwise 409 names the node holding the track. 429 when this node's processing queue
// (`recording.processing.max_queued`) is full.
//
// `POST /v1/recordings/mixdown`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:write.
func (c *Client) MixdownRecordings(ctx context.Context, body MixdownRecordingsRequest, opts ...RequestOption) (*Recording, error) {
	var q url.Values
	var out Recording
	if err := c.doJSON(ctx, "POST", "/v1/recordings/mixdown", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// TranscribeRecording — Queue speech-to-text of a stored recording
//
// Requires an `[stt]` provider on the node. A participant track is transcribed as one speaker; a
// mixdown is transcribed from its source tracks one by one, so every segment names its speaker.
// Audio is decoded in `recording.processing.stt_chunk_secs` chunks cut on silence and resampled to
// `stt_sample_rate`. Returns the transcript row with `status = queued`; poll `GET .../transcript`
// or wait for `recording.processed` with `job = transcript`. 409 while a transcript of this
// recording is already queued/running or the recording is not `ready`; a `failed` transcript may
// be requested again.
//
// `POST /v1/recordings/{recording_id}/transcribe`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:write.
func (c *Client) TranscribeRecording(ctx context.Context, recordingID string, opts ...RequestOption) (*RecordingTranscript, error) {
	var q url.Values
	var out RecordingTranscript
	if err := c.doJSON(ctx, "POST", "/v1/recordings/"+url.PathEscape(recordingID)+"/transcribe", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRecordingTranscript — Transcript of a recording (JSON, SRT or WebVTT)
//
// `format=json` (default) returns the row in any state; `srt`/`vtt` render the segments as
// subtitles (speaker as a `<v uuid>` voice tag) and require `status = ready` (409 otherwise).
//
// `GET /v1/recordings/{recording_id}/transcript`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:read.
//
// When the server answers with application/x-subrip, text/vtt (non-JSON `format`) this call fails; use the `GetRecordingTranscriptRaw` instead.
func (c *Client) GetRecordingTranscript(ctx context.Context, recordingID string, query *GetRecordingTranscriptQuery, opts ...RequestOption) (*RecordingTranscript, error) {
	q := url.Values{}
	if query != nil {
		if query.Format != nil {
			q.Set("format", string(*query.Format))
		}
	}
	var out RecordingTranscript
	if err := c.doJSON(ctx, "GET", "/v1/recordings/"+url.PathEscape(recordingID)+"/transcript", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRecordingTranscriptRaw — Transcript of a recording (JSON, SRT or WebVTT)
//
// `format=json` (default) returns the row in any state; `srt`/`vtt` render the segments as
// subtitles (speaker as a `<v uuid>` voice tag) and require `status = ready` (409 otherwise).
//
// `GET /v1/recordings/{recording_id}/transcript`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: recordings:read.
//
// Returns the raw body (application/json, application/x-subrip, text/vtt).
func (c *Client) GetRecordingTranscriptRaw(ctx context.Context, recordingID string, query *GetRecordingTranscriptQuery, opts ...RequestOption) (*RawResponse, error) {
	q := url.Values{}
	if query != nil {
		if query.Format != nil {
			q.Set("format", string(*query.Format))
		}
	}
	return c.doRaw(ctx, "GET", "/v1/recordings/"+url.PathEscape(recordingID)+"/transcript", q, nil, opts, "*/*")
}

// ListUserReadMarkers — Read markers of a user
//
// With `channel_id` or `peer_user_id`: the user's marker in that conversation (`null` if they
// never read there) and how many messages from others lie after it (capped at
// `chat.unread_count_cap`). Without a selector: every marker of the user. Requires `chat.persist =
// true` (otherwise `404`).
//
// `GET /v1/users/{user_id}/read-markers`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:read.
func (c *Client) ListUserReadMarkers(ctx context.Context, userID string, query *ListUserReadMarkersQuery, opts ...RequestOption) (json.RawMessage, error) {
	q := url.Values{}
	if query != nil {
		if query.ChannelID != nil {
			q.Set("channel_id", *query.ChannelID)
		}
		if query.PeerUserID != nil {
			q.Set("peer_user_id", *query.PeerUserID)
		}
	}
	var out json.RawMessage
	err := c.doJSON(ctx, "GET", "/v1/users/"+url.PathEscape(userID)+"/read-markers", q, nil, &out, opts)
	return out, err
}

// PutUserReadMarker — Advance a user's read marker
//
// Marks everything in the conversation up to `message_id` as read on the user's behalf (for
// example after a support agent answered for them). Markers only move forward: an older or equal
// position is accepted but `moved` is `false`. The message must belong to the selected
// conversation of that user, otherwise `404`. Every device of the user receives `ChatReadMarker`;
// with `chat.read_receipts` so do the channel members / the peer. Requires `chat.persist = true`.
//
// `PUT /v1/users/{user_id}/read-markers`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:write.
func (c *Client) PutUserReadMarker(ctx context.Context, userID string, body ReadMarkerRequest, opts ...RequestOption) (*PutUserReadMarkerResponse, error) {
	var q url.Values
	var out PutUserReadMarkerResponse
	if err := c.doJSON(ctx, "PUT", "/v1/users/"+url.PathEscape(userID)+"/read-markers", q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChannelReadMarkers — Read markers in a channel
//
// Reading position of every user who marked something read in the channel (newest position first).
// Requires `chat.persist = true` (otherwise `404`).
//
// `GET /v1/channels/{channel_id}/read-markers`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:read.
func (c *Client) ListChannelReadMarkers(ctx context.Context, channelID string, opts ...RequestOption) (*ListChannelReadMarkersResponse, error) {
	var q url.Values
	var out ListChannelReadMarkersResponse
	if err := c.doJSON(ctx, "GET", "/v1/channels/"+url.PathEscape(channelID)+"/read-markers", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchChannelMessages — Search channel messages
//
// Full-text search over stored messages (`chat.persist = true`, `chat.search = true`; otherwise
// `404` / `501`). Deleted messages never match. Matches are newest first; `next_before` continues
// to older matches (`next_after` is never set for a search page).
//
// `GET /v1/channels/{channel_id}/messages/search`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:read.
func (c *Client) SearchChannelMessages(ctx context.Context, channelID string, query *SearchChannelMessagesQuery, opts ...RequestOption) (*ChatHistoryPage, error) {
	q := url.Values{}
	if query != nil {
		if query.Q != nil {
			q.Set("q", *query.Q)
		}
		if query.FromUserID != nil {
			q.Set("from_user_id", *query.FromUserID)
		}
		if query.Before != nil {
			q.Set("before", *query.Before)
		}
		if query.Limit != nil {
			q.Set("limit", strconv.FormatInt(*query.Limit, 10))
		}
	}
	var out ChatHistoryPage
	if err := c.doJSON(ctx, "GET", "/v1/channels/"+url.PathEscape(channelID)+"/messages/search", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchUserMessages — Search a user's messages
//
// Full-text search over stored messages (`chat.persist = true`, `chat.search = true`; otherwise
// `404` / `501`). Deleted messages never match. Matches are newest first; `next_before` continues
// to older matches (`next_after` is never set for a search page). Without `peer` the search covers
// every directed message the user sent or received (moderation view).
//
// `GET /v1/users/{user_id}/messages/search`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:read.
func (c *Client) SearchUserMessages(ctx context.Context, userID string, query *SearchUserMessagesQuery, opts ...RequestOption) (*ChatHistoryPage, error) {
	q := url.Values{}
	if query != nil {
		if query.Q != nil {
			q.Set("q", *query.Q)
		}
		if query.FromUserID != nil {
			q.Set("from_user_id", *query.FromUserID)
		}
		if query.Before != nil {
			q.Set("before", *query.Before)
		}
		if query.Limit != nil {
			q.Set("limit", strconv.FormatInt(*query.Limit, 10))
		}
		if query.Peer != nil {
			q.Set("peer", *query.Peer)
		}
	}
	var out ChatHistoryPage
	if err := c.doJSON(ctx, "GET", "/v1/users/"+url.PathEscape(userID)+"/messages/search", q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMessage — Get a stored message
//
// One stored message of the app with its reaction tallies; deleted messages are returned as
// tombstones (`deleted_at` set, empty `text`). Requires `chat.persist = true` (otherwise `404`).
//
// `GET /v1/messages/{message_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:read.
func (c *Client) GetMessage(ctx context.Context, messageID string, opts ...RequestOption) (*ChatMessage, error) {
	var q url.Values
	var out ChatMessage
	if err := c.doJSON(ctx, "GET", "/v1/messages/"+url.PathEscape(messageID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// EditMessage — Edit a message
//
// Operator edit of any stored, not deleted message of the app: replaces `text` and `metadata`,
// sets `edited_at`. The author / `chat.edit_window_secs` rules and the text filters apply to
// players, not to this endpoint. Everyone who sees the message receives `ChatMessageUpdated`; the
// id and `sent_at` never change.
//
// `PATCH /v1/messages/{message_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:write.
func (c *Client) EditMessage(ctx context.Context, messageID string, body EditMessageRequest, opts ...RequestOption) (*ChatMessage, error) {
	var q url.Values
	var out ChatMessage
	if err := c.doJSON(ctx, "PATCH", "/v1/messages/"+url.PathEscape(messageID), q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteMessage — Delete a message
//
// Operator deletion: the message becomes a tombstone (`deleted_at`, `deleted_by` = nil system
// user) that keeps its id and position in history but loses text, metadata and reactions. Deleted
// messages are excluded from search, unread counts and offline replay. Deleting again is `404`.
//
// `DELETE /v1/messages/{message_id}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:write.
func (c *Client) DeleteMessage(ctx context.Context, messageID string, opts ...RequestOption) (*ChatMessage, error) {
	var q url.Values
	var out ChatMessage
	if err := c.doJSON(ctx, "DELETE", "/v1/messages/"+url.PathEscape(messageID), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// AddMessageReaction — Add a reaction on behalf of a user
//
// Sets `user_id`'s `reaction` on the message (idempotent: repeating is `changed: false`). A
// message carries at most `chat.reactions_per_message` distinct reactions (`400` beyond that);
// direct messages accept reactions only from their two parties (`404` otherwise). Changes fan out
// as `ChatReactionChanged` to everyone who sees the message.
//
// `PUT /v1/messages/{message_id}/reactions/{reaction}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:write.
func (c *Client) AddMessageReaction(ctx context.Context, messageID string, reaction string, body ReactionRequest, opts ...RequestOption) (*ReactionChange, error) {
	var q url.Values
	var out ReactionChange
	if err := c.doJSON(ctx, "PUT", "/v1/messages/"+url.PathEscape(messageID)+"/reactions/"+url.PathEscape(reaction), q, body, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveMessageReaction — Remove a user's reaction
//
// Clears `user_id`'s `reaction` from the message (idempotent).
//
// `DELETE /v1/messages/{message_id}/reactions/{reaction}`
// Auth: ApiKeyHeader | ApiKeyBearer.
// Permissions: chat:write.
func (c *Client) RemoveMessageReaction(ctx context.Context, messageID string, reaction string, query *RemoveMessageReactionQuery, opts ...RequestOption) (*ReactionChange, error) {
	q := url.Values{}
	if query != nil {
		if query.UserID != nil {
			q.Set("user_id", *query.UserID)
		}
	}
	var out ReactionChange
	if err := c.doJSON(ctx, "DELETE", "/v1/messages/"+url.PathEscape(messageID)+"/reactions/"+url.PathEscape(reaction), q, nil, &out, opts); err != nil {
		return nil, err
	}
	return &out, nil
}
