export {
  AurixClient,
  DEFAULT_DUCKING,
  channelInfoFromJoinAck,
  defaultAudioConstraints,
  parseDucking,
  encodeChatCursor,
  reconnectEndpoint,
  transmissionFromWire,
  transmissionToWire,
} from './client.js';
export { AurixBridge, errorInfo } from './bridge.js';
export {
  E2EE_CONSTANTS,
  E2eeError,
  E2eeGroup,
  E2eeIdentity,
  E2eePeerKeys,
  E2eeReplayState,
  E2eeSenderKey,
  FrameCrypto,
  attachEncodedStreams,
  base64ToBytes,
  bytesToBase64,
  bytesToHex,
  detectE2eeSupport,
  e2eeFingerprint,
  e2eeWorkerMain,
  e2eeWorkerSource,
  hexToBytes,
  hkdfSha256,
  x25519,
} from './e2ee.js';
export type {
  E2eeFrameStats,
  E2eeMode,
  E2eeOutgoing,
  E2eePeerChange,
  E2eeSupport,
  E2eeTransformApi,
  E2eeWorkerMessage,
  E2eeWorkerReply,
} from './e2ee.js';
export {
  SpatialRenderer,
  createAudioContext,
  directionFromListener,
  distanceGain,
  renderParams,
} from './spatial.js';
export type { Direction, RenderInputs, RenderParams, SpatialRendererOptions } from './spatial.js';
export type { AurixBridgeOptions, BridgeClientOptions, BridgeErrorInfo, BridgeEvent } from './bridge.js';
export {
  AUDIO_LEVEL_SILENCE,
  AudioLevelMeter,
  VoiceActivityDetector,
  decodeAudioLevel,
  encodeAudioLevel,
  rms,
} from './audio.js';
export type { AudioLevelMeterOptions, AudioLevelSample } from './audio.js';
export {
  DEFAULT_AUDIO_POLICY,
  applyOpusSenderPreferences,
  audioPoliciesEqual,
  mergeAllAudioPolicies,
  mergeAudioPolicies,
  negotiatedOpusPreferences,
  opusPlaybackRateHz,
  parseAudioPolicy,
  resolveOpusSenderPreferences,
} from './opus.js';
export type {
  AudioPolicy,
  OpusBandwidth,
  OpusBrowserOptions,
  OpusSenderPreferences,
  OpusSignal,
} from './opus.js';
export {
  LossWindow,
  RttTracker,
  assembleClientStats,
  barsFromR,
  lossPercent,
  mosFromR,
  networkQualityFromWire,
  rFactor,
} from './quality.js';
export type { ClientStats, NetworkQuality, NetworkQualityWire, RtcStatsInput, RttSnapshot } from './quality.js';
export type {
  AurixClientOptions,
  AurixEvents,
  ChannelInfo,
  ChannelScope,
  ChatMessage,
  ChatReaction,
  ChatReactionChange,
  ChatScope,
  EditMessageOptions,
  ConnectionState,
  DuckingConfig,
  HistoryOptions,
  HistoryPage,
  MediaTransport,
  MediaTransportPreference,
  ReadMarker,
  ReadMarkers,
  Participant,
  ParticipantStreamInfo,
  ReceiverPreferences,
  ReconnectPolicy,
  SearchOptions,
  SearchPage,
  SendMessageOptions,
  SessionInfo,
  SetTranslationOptions,
  SpeakOptions,
  SpeechRequest,
  Transcript,
  TranscriptWord,
  TranslationInfo,
  TranslationPrefs,
  TransmissionMode,
  TtsDestination,
  TtsState,
  TtsStatus,
  WebTransportAdvertisement,
  WebTransportClientOptions,
} from './client.js';
export {
  AURX_AUTH_TAG_SIZE,
  AURX_HEADER_SIZE,
  AURX_MAX_PACKET_SIZE,
  AURX_PROTOCOL_VERSION,
  AurxFlags,
  AurxKeys,
  AurxPacketType,
  ReplayWindow,
  SequenceLoss,
  audioHeader,
  audioLevelByte,
  channelIdHash,
  crc32,
  decodeDirection,
  decodePacket,
  decodeVolumeByte,
  downlinkCodec,
  encodeHeader,
  heartbeatHeader,
  opusPacketIsStereo,
  parseDownlinkAudio,
  sessionBindHeader,
  sessionBindPayload,
  uuidBytes,
} from './aurx.js';
export type { AurxDirection, AurxHeader, AurxPacket, DownlinkAudio, DownlinkCodec } from './aurx.js';
export { decodeG711, G711_FRAME_SIZES, G711_SAMPLE_RATE, G711Upsampler, type G711Law } from './g711.js';
export {
  AURX_FRAME_SAMPLES,
  AURX_SAMPLE_RATE,
  AurxCapture,
  AurxPlayback,
  aurxOpusSupported,
  aurxWorkletSource,
  loadAurxWorklet,
  opusConfigFor,
  supportsAurxAudio,
} from './aurx-audio.js';
export type { AurxCaptureFrame, AurxOpusConfig, AurxPlaybackStats } from './aurx-audio.js';
export { AurxWebTransport, certificateHashes, detectWebTransportSupport } from './webtransport.js';
export type {
  AurxWebTransportEvents,
  AurxWebTransportOptions,
  AurxWebTransportStats,
  WebTransportConstructor,
  WebTransportSessionKeys,
  WebTransportSupport,
} from './webtransport.js';
export {
  MAX_DISTORTION_DRIVE,
  MAX_FILTER_HZ,
  MAX_FORMANT_SEMITONES,
  MAX_PITCH_SEMITONES,
  MAX_RING_MOD_HZ,
  MAX_TREMOLO_HZ,
  MIN_FILTER_HZ,
  VOICE_EFFECTS_BYPASS,
  VOICE_EFFECTS_PROCESSOR,
  VOICE_EFFECT_PRESETS,
  VoiceEffectChain,
  createVoiceEffectsNode,
  isVoiceEffectsBypass,
  loadVoiceEffectsWorklet,
  sanitizeVoiceEffects,
  supportsVoiceEffects,
  voiceEffectPreset,
  voiceEffectsWorkletSource,
} from './effects.js';
export type {
  ResolvedVoiceEffectParams,
  VoiceEffectParams,
  VoiceEffectPreset,
  VoiceEffectStage,
  VoiceEffectsWorkletMessage,
} from './effects.js';
export {
  VISEMES,
  VISEME_COUNT,
  VISEME_PROCESSOR,
  VisemeAnalyzer,
  createVisemeNode,
  loadVisemeWorklet,
  silentVisemeFrame,
  supportsVisemes,
  visemeWorkletSource,
} from './visemes.js';
export type { Viseme, VisemeFrame, VisemeWorkletFrame } from './visemes.js';
export type {
  AudioPolicyWire,
  ChannelRole,
  DuckingConfigWire,
  ChatMessageWire,
  ChatReadMarkerWire,
  ClientMessage,
  JsonValue,
  LocalMute,
  ModerationAction,
  Orientation3D,
  ParticipantBrief,
  ParticipantEnergy,
  ParticipantStreamWire,
  ParticipantVolume,
  Position3D,
  PositionalConfigWire,
  RecordingConsent,
  ServerMessage,
  TranscriptWire,
  TranscriptWordWire,
  TranslationInfoWire,
  TransmissionModeWire,
  TtsDestinationWire,
  TtsStateWire,
  TurnCredentials,
  UnknownMessage,
  UserPosition,
} from './protocol.js';
export {
  AURIX_SUBPROTOCOL,
  BEARER_SUBPROTOCOL_PREFIX,
  DEVICE_SUBPROTOCOL_PREFIX,
  MAX_PARTICIPANT_VOLUME,
  RESUME_SUBPROTOCOL_PREFIX,
  SYNTH_SSRC_FLAG,
  SYSTEM_USER_ID,
  isValidDeviceId,
  parseServerMessage,
} from './protocol.js';
export {
  InputPipeline,
  MAX_INPUT_GAIN,
  enumerateAudioDevices,
  supportsOutputSelection,
} from './devices.js';
export type {
  AudioDeviceInfo,
  AudioDevices,
  AudioInjectionOptions,
  AudioInjectionSource,
} from './devices.js';
export {
  DEFAULT_PROBE_SAMPLES,
  DEFAULT_PROBE_TIMEOUT_MS,
  DEFAULT_RTT_TOLERANCE_MS,
  discoverRegions,
  parseRegionsResponse,
  probeRtt,
  rankRegions,
} from './regions.js';
export type {
  DiscoverRegionsOptions,
  DiscoveredRegions,
  GeoLocation,
  ProbeOptions,
  ProbedRegion,
  RankOptions,
  RegionEndpoint,
  RegionsResponse,
} from './regions.js';
