/* Aurix native voice client — stable C ABI. Generated by cbindgen from crates/aurix-client; do not edit (run `cargo run -p aurix-client --example gen_header`). */

#ifndef AURIX_CLIENT_H
#define AURIX_CLIENT_H

/* Generated with cbindgen:0.29.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#define EncoderSettings_MIN_BITRATE 6000

/**
 * libopus clamps a mono stream's bitrate to 300 kbit/s internally.
 */
#define EncoderSettings_MAX_BITRATE 300000

/**
 * libopus' ceiling for a stereo stream.
 */
#define EncoderSettings_MAX_STEREO_BITRATE 510000

/**
 * libopus' own default.
 */
#define EncoderSettings_DEFAULT_COMPLEXITY 9

/**
 * Bytes needed for `aurix_uuid_format` (36 characters + NUL).
 */
#define AURIX_UUID_STRING_LEN 37

/**
 * Capacity of fixed-size UTF-8 name buffers in this ABI (including the NUL).
 */
#define AURIX_NAME_LEN 128

/**
 * Bit set on the SSRC of a synthesized (text-to-speech) voice; the base SSRC is the owner's.
 */
#define AURIX_SYNTH_SSRC_FLAG 2147483648

/**
 * Everything on the wire is Opus at 48 kHz; `mix_output` produces this rate.
 */
#define AURIX_SAMPLE_RATE 48000

/**
 * Samples per channel in one 20 ms frame at `AURIX_SAMPLE_RATE`.
 */
#define AURIX_FRAME_SAMPLES 960

/**
 * Capacity of fixed-size URL buffers in this ABI (including the NUL).
 */
#define AURIX_URL_LEN 512

/**
 * RTT differences below this are treated as ties (network noise, not a better region).
 */
#define DEFAULT_RTT_TOLERANCE_MS 15.0

/**
 * Return code of fallible calls; details via `aurix_last_error`.
 */
typedef enum AurixResult {
  AURIX_OK = 0,
  AURIX_NULL_POINTER = 1,
  AURIX_INVALID_ARGUMENT = 2,
  AURIX_NOT_CONNECTED = 3,
  AURIX_CLOSED = 4,
  AURIX_TRANSPORT = 5,
  AURIX_UNAUTHORIZED = 6,
  AURIX_TIMEOUT = 7,
  AURIX_SERVER_REJECTED = 8,
  AURIX_CODEC = 9,
  AURIX_PROTOCOL = 10,
} AurixResult;

/**
 * Opus coding bandwidth (`OPUS_SET_MAX_BANDWIDTH`), widest band the encoder may use.
 */
typedef enum AurixOpusBandwidth {
  /**
   * 4 kHz audio band.
   */
  AURIX_BANDWIDTH_NARROWBAND = 0,
  /**
   * 6 kHz.
   */
  AURIX_BANDWIDTH_MEDIUMBAND = 1,
  /**
   * 8 kHz.
   */
  AURIX_BANDWIDTH_WIDEBAND = 2,
  /**
   * 12 kHz.
   */
  AURIX_BANDWIDTH_SUPERWIDEBAND = 3,
  /**
   * 20 kHz.
   */
  AURIX_BANDWIDTH_FULLBAND = 4,
} AurixOpusBandwidth;

/**
 * Opus content hint (`OPUS_SET_SIGNAL`).
 */
typedef enum AurixOpusSignal {
  AURIX_SIGNAL_AUTO = 0,
  AURIX_SIGNAL_VOICE = 1,
  AURIX_SIGNAL_MUSIC = 2,
} AurixOpusSignal;

/**
 * Noise suppression strength (dry/wet blend of the RNNoise output).
 */
typedef enum AurixNoiseSuppression {
  AURIX_NOISE_SUPPRESSION_OFF = 0,
  AURIX_NOISE_SUPPRESSION_LOW = 1,
  AURIX_NOISE_SUPPRESSION_MODERATE = 2,
  AURIX_NOISE_SUPPRESSION_HIGH = 3,
} AurixNoiseSuppression;

/**
 * Media link selection policy (`AurixClientConfig::media_path`).
 */
typedef enum AurixMediaPathPolicy {
  /**
   * UDP first; WebSocket tunnel when UDP is blocked; back to UDP when it answers again.
   */
  AURIX_MEDIA_PATH_AUTO = 0,
  AURIX_MEDIA_PATH_UDP_ONLY = 1,
  AURIX_MEDIA_PATH_TUNNEL_ONLY = 2,
} AurixMediaPathPolicy;

typedef enum AurixConnectionState {
  AURIX_STATE_DISCONNECTED = 0,
  AURIX_STATE_CONNECTING = 1,
  AURIX_STATE_CONNECTED = 2,
  AURIX_STATE_MEDIA_BOUND = 3,
  AURIX_STATE_RECONNECTING = 4,
  AURIX_STATE_FAILED = 5,
} AurixConnectionState;

/**
 * Link the media currently travels over.
 */
typedef enum AurixMediaPath {
  /**
   * No media link yet (before `AurixEventMediaBound`).
   */
  AURIX_MEDIA_NONE = 0,
  /**
   * Native AURX over UDP.
   */
  AURIX_MEDIA_UDP = 1,
  /**
   * AURX packets as binary frames on the control WebSocket (TCP; higher latency under
   * loss).
   */
  AURIX_MEDIA_TUNNEL = 2,
} AurixMediaPath;

typedef enum AurixEventType {
  /**
   * `state`.
   */
  AURIX_EVENT_STATE_CHANGED = 0,
  /**
   * `session`.
   */
  AURIX_EVENT_SESSION_READY = 1,
  AURIX_EVENT_MEDIA_BOUND = 2,
  /**
   * `request_id`, `channel_id`, `participants`, `flag` = transcription enabled, `flag2` =
   * content-safety monitoring (disclose it to the player).
   */
  AURIX_EVENT_CHANNEL_JOINED = 3,
  /**
   * `channel_id`.
   */
  AURIX_EVENT_CHANNEL_LEFT = 4,
  /**
   * `channel_id`, `participants[0]`.
   */
  AURIX_EVENT_PARTICIPANT_JOINED = 5,
  /**
   * `channel_id`, `user_id`.
   */
  AURIX_EVENT_PARTICIPANT_LEFT = 6,
  /**
   * `channel_id`, `user_id`, `flag` = muted, `flag2` = server muted.
   */
  AURIX_EVENT_PARTICIPANT_MUTE_CHANGED = 7,
  /**
   * `channel_id`, `user_id`, `flag` = speaking.
   */
  AURIX_EVENT_PARTICIPANT_SPEAKING = 8,
  /**
   * `channel_id`, `participants[i].user_id/energy`.
   */
  AURIX_EVENT_CHANNEL_ENERGY = 9,
  /**
   * `flag` = speaking.
   */
  AURIX_EVENT_LOCAL_SPEAKING = 10,
  /**
   * `transmission`, `channel_id` for single.
   */
  AURIX_EVENT_TRANSMISSION_CHANGED = 11,
  /**
   * `channel_id` (zero UUID = no focus).
   */
  AURIX_EVENT_CHANNEL_FOCUS_CHANGED = 12,
  /**
   * `user_id`, `flag` = blocked.
   */
  AURIX_EVENT_USER_BLOCK_CHANGED = 13,
  /**
   * `channel_id`, `recording_id`, `flag` = active, `flag2` = live stream (not a stored
   * file), `user_id` = initiator (zero UUID = operator).
   */
  AURIX_EVENT_RECORDING = 14,
  /**
   * `number` = bitrate bps, `message` = reason.
   */
  AURIX_EVENT_BITRATE_CHANGED = 15,
  /**
   * `channel_id`, `message` = reason.
   */
  AURIX_EVENT_KICKED = 16,
  /**
   * `request_id`, `channel_id`, `user_id`, `moderation_action`.
   */
  AURIX_EVENT_MODERATION_APPLIED = 17,
  /**
   * `chat`.
   */
  AURIX_EVENT_CHAT_MESSAGE = 18,
  /**
   * `channel_id`, `user_id`, `flag` = typing.
   */
  AURIX_EVENT_PARTICIPANT_TYPING = 19,
  /**
   * `transcript`.
   */
  AURIX_EVENT_TRANSCRIPT = 20,
  /**
   * `tts`.
   */
  AURIX_EVENT_TTS_STATUS = 21,
  /**
   * `channel_id`, `positions` via `json`.
   */
  AURIX_EVENT_POSITIONS = 22,
  /**
   * `channel_id`, `code`, `message`.
   */
  AURIX_EVENT_REJOIN_FAILED = 23,
  /**
   * `request_id`, `code`, `message`.
   */
  AURIX_EVENT_REQUEST_FAILED = 24,
  /**
   * `code`, `message`.
   */
  AURIX_EVENT_SERVER_ERROR = 25,
  /**
   * `number` = attempt, `number2` = delay ms, `message` = cause.
   */
  AURIX_EVENT_RECOVERING = 26,
  /**
   * `flag` = resumed (else channels were re-joined with fresh state), `flag2` = migrated
   * (resumed on another node; `aurix_client_endpoint` names it).
   */
  AURIX_EVENT_RECOVERED = 27,
  /**
   * `message` = reason.
   */
  AURIX_EVENT_FAILED_TO_RECOVER = 28,
  /**
   * `message` = reason.
   */
  AURIX_EVENT_DISCONNECTED = 29,
  /**
   * `network_quality`.
   */
  AURIX_EVENT_NETWORK_QUALITY = 30,
  /**
   * `audio_policy`: merged policy of the joined channels changed.
   */
  AURIX_EVENT_AUDIO_POLICY_CHANGED = 31,
  /**
   * `audio_codec`: the server switched this session's codec (`aurix_event_audio_codec`).
   */
  AURIX_EVENT_AUDIO_CODEC_CHANGED = 32,
  /**
   * `media_path` (`aurix_event_media_path`), `message` = why: emitted after every
   * `MediaBound` and on each mid-session UDP ↔ tunnel switch.
   */
  AURIX_EVENT_MEDIA_PATH_CHANGED = 33,
  /**
   * `downlink_mode` (`aurix_event_downlink_mode`): the server acknowledged a downlink
   * mode; a fresh session reports `Streams` and the requested mode is re-applied.
   */
  AURIX_EVENT_DOWNLINK_MODE_CHANGED = 34,
  /**
   * `message` = the WebSocket URL the client now talks to: a failover endpoint answered
   * while the previous node did not. Precedes that connection's `SessionReady`.
   */
  AURIX_EVENT_ENDPOINT_CHANGED = 35,
} AurixEventType;

typedef enum AurixTransmissionMode {
  /**
   * Microphone reaches no channel.
   */
  AURIX_TRANSMIT_NONE = 0,
  /**
   * Microphone reaches one channel (`channel_id` argument).
   */
  AURIX_TRANSMIT_SINGLE = 1,
  /**
   * Microphone reaches every joined channel.
   */
  AURIX_TRANSMIT_ALL = 2,
} AurixTransmissionMode;

/**
 * Session audio codec (see `aurix_client_set_audio_codec`).
 */
typedef enum AurixAudioCodec {
  /**
   * Default: 48 kHz Opus.
   */
  AURIX_CODEC_OPUS = 0,
  /**
   * G.711 μ-law fallback: 8 kHz, 64 kbit/s, no Opus CPU cost, telephone quality.
   */
  AURIX_CODEC_PCMU = 1,
} AurixAudioCodec;

/**
 * How the node delivers other speakers to this session (see
 * `aurix_client_set_downlink_mode`).
 */
typedef enum AurixDownlinkMode {
  /**
   * Default: one stream per audible speaker, mixed by this client.
   */
  AURIX_DOWNLINK_STREAMS = 0,
  /**
   * One server-mixed stereo stream per channel (mutes / volumes / focus / positional gains
   * applied by the node); E2EE speakers still arrive as separate streams.
   */
  AURIX_DOWNLINK_MIXED = 1,
} AurixDownlinkMode;

typedef enum AurixModerationAction {
  AURIX_MODERATION_KICK = 0,
  AURIX_MODERATION_MUTE = 1,
  AURIX_MODERATION_UNMUTE = 2,
} AurixModerationAction;

typedef enum AurixRole {
  AURIX_ROLE_LISTENER = 0,
  AURIX_ROLE_SPEAKER = 1,
  AURIX_ROLE_MODERATOR = 2,
  AURIX_ROLE_ADMINISTRATOR = 3,
} AurixRole;

typedef enum AurixTtsState {
  AURIX_TTS_QUEUED = 0,
  AURIX_TTS_PLAYING = 1,
  AURIX_TTS_FINISHED = 2,
  AURIX_TTS_CANCELLED = 3,
  AURIX_TTS_FAILED = 4,
} AurixTtsState;

typedef enum AurixRecordingConsent {
  AURIX_CONSENT_ACCEPTED = 0,
  AURIX_CONSENT_DECLINED = 1,
} AurixRecordingConsent;

typedef enum AurixTtsDestination {
  /**
   * Heard by the channel (as this participant's voice) and locally.
   */
  AURIX_TTS_BOTH = 0,
  AURIX_TTS_CHANNEL = 1,
  AURIX_TTS_LOCAL = 2,
} AurixTtsDestination;

/**
 * Opaque voice client. One per player/session.
 */
typedef struct AurixClient AurixClient;

/**
 * Opaque standalone DSP processor (see `aurix_dsp_create`).
 */
typedef struct AurixDsp AurixDsp;

/**
 * Opaque event; read with the `aurix_event_*` accessors and release with `aurix_event_free`.
 */
typedef struct AurixEvent AurixEvent;

/**
 * Opaque bare Opus decoder (see `aurix_opus_decoder_create`).
 */
typedef struct AurixOpusDecoder AurixOpusDecoder;

/**
 * Opaque bare Opus encoder (see `aurix_opus_encoder_create`).
 */
typedef struct AurixOpusEncoder AurixOpusEncoder;

/**
 * Opaque, mutable list of regions; release with `aurix_regions_free`.
 */
typedef struct AurixRegionList AurixRegionList;

/**
 * 128-bit id (session, channel, user, recording) in RFC 4122 byte order.
 */
typedef struct AurixUuid {
  uint8_t bytes[16];
} AurixUuid;

/**
 * Uplink Opus encoder settings. Out-of-range values are clamped, never rejected.
 */
typedef struct AurixEncoderSettings {
  /**
   * 6000..=300000 for mono, ..=510000 for stereo (libopus' ceilings).
   */
  uint32_t bitrate_bps;
  /**
   * 0..=10 (10 = best quality, most CPU).
   */
  uint8_t complexity;
  enum AurixOpusBandwidth max_bandwidth;
  enum AurixOpusSignal signal;
  /**
   * Variable bitrate; `false` = hard CBR.
   */
  bool vbr;
  /**
   * Constrained VBR (frames stay within the bitrate's byte budget).
   */
  bool constrained_vbr;
  /**
   * In-band forward error correction.
   */
  bool fec;
  /**
   * Loss the FEC is tuned for, 0..=100 %.
   */
  uint8_t expected_loss_percent;
  /**
   * Discontinuous transmission during silence.
   */
  bool dtx;
  /**
   * 1 (mono voice, default) or 2 (stereo music / broadcast). Only honoured in channels
   * whose policy allows `stereo`; PCMU is always mono. Other values are read as 1.
   */
  uint8_t channels;
} AurixEncoderSettings;

/**
 * Capture DSP configuration. Out-of-range values are clamped, never rejected. The chain adds
 * 10 ms of latency when the echo canceller is on; everything off is a pass-through.
 */
typedef struct AurixDspConfig {
  /**
   * 80 Hz second-order high-pass.
   */
  bool high_pass;
  /**
   * Acoustic echo cancellation against the audio fed by `aurix_client_mix_output_*` /
   * `aurix_client_push_render_*`.
   */
  bool echo_cancellation;
  /**
   * Echo tail modelled by the adaptive filter, 40..=`AURIX_DSP_MAX_ECHO_TAIL_MS`.
   */
  uint32_t echo_tail_ms;
  /**
   * Initial playback→capture delay hint, 0..=`AURIX_DSP_MAX_STREAM_DELAY_MS`; refined at
   * runtime by the delay estimator.
   */
  uint32_t stream_delay_ms;
  enum AurixNoiseSuppression noise_suppression;
  /**
   * Speech-gated automatic gain control with a soft limiter.
   */
  bool agc;
  /**
   * AGC target speech level, dBFS RMS, -30..=-6.
   */
  float agc_target_dbfs;
  /**
   * Maximum AGC boost, 0..=40 dB.
   */
  float agc_max_gain_db;
} AurixDspConfig;

/**
 * Connection parameters. Fill with `aurix_client_config_default`, then set `ws_url`/`token`.
 */
typedef struct AurixClientConfig {
  /**
   * `ws://host:port/ws` or `wss://…` (required, borrowed).
   */
  const char *ws_url;
  /**
   * Session JWT or one-time `login` action token (required, borrowed; copied).
   */
  const char *token;
  bool auto_reconnect;
  /**
   * 0 = never give up.
   */
  uint32_t reconnect_max_attempts;
  uint32_t reconnect_initial_delay_ms;
  uint32_t reconnect_max_delay_ms;
  uint32_t request_timeout_ms;
  uint32_t ping_interval_ms;
  uint32_t heartbeat_interval_ms;
  /**
   * Uplink Opus encoder before any channel policy applies.
   */
  struct AurixEncoderSettings encoder;
  /**
   * Adopt joined channels' audio policy (bitrate/FEC/DTX/bandwidth/signal and the complexity
   * hint unless pinned with `aurix_client_set_complexity`). Server bitrate commands apply
   * either way.
   */
  bool follow_channel_policy;
  /**
   * Jitter buffer depth before playout starts (20 ms frames).
   */
  uint32_t jitter_target_frames;
  uint32_t jitter_max_frames;
  /**
   * Only send frames the voice activity detector marks as speech.
   */
  bool vad_gate;
  /**
   * Tokio worker threads for the control plane (1 is plenty).
   */
  uint32_t worker_threads;
  /**
   * Capture DSP (high-pass / echo cancellation / noise suppression / AGC) before the VAD
   * and encoder; `aurix_dsp_config_default` = everything on, `aurix_dsp_config_bypass` for
   * hosts with their own processing. Changeable later with `aurix_client_set_dsp`.
   */
  struct AurixDspConfig dsp;
  /**
   * Which link carries media: UDP with the WebSocket tunnel as fallback (default), UDP
   * only, or tunnel only.
   */
  enum AurixMediaPathPolicy media_path;
  /**
   * `Auto`: unanswered UDP heartbeats in a row before media moves to the tunnel (0 = never
   * fall back mid-session; the default 3 ≈ 15 s with 5 s heartbeats).
   */
  uint32_t udp_fallback_lost_heartbeats;
  /**
   * `Auto`: how often a tunnelled session re-probes UDP and moves back when it answers
   * (0 = never; stays tunnelled until the next connect).
   */
  uint32_t udp_reprobe_interval_ms;
} AurixClientConfig;

/**
 * Facts about the current session.
 */
typedef struct AurixSessionInfo {
  struct AurixUuid session_id;
  /**
   * This client's own SSRC (also the base of its TTS voice SSRC).
   */
  uint32_t ssrc;
  /**
   * How long the server keeps the session resumable after a drop.
   */
  uint32_t resume_grace_ms;
  /**
   * The latest (re)connect resumed the previous session.
   */
  bool resumed;
  /**
   * Zero UUID when the token carries no `sub`.
   */
  struct AurixUuid user_id;
  /**
   * The node accepts media over the control WebSocket (fallback when UDP is blocked).
   */
  bool media_tunnel;
  /**
   * The node can deliver one server-mixed stream per channel
   * (`aurix_client_set_downlink_mode`).
   */
  bool downlink_mix;
  /**
   * The latest (re)connect resumed the session on a *different* node (same session id
   * and SSRC, new media key/endpoint). See `aurix_client_endpoint`.
   */
  bool migrated;
} AurixSessionInfo;

/**
 * Channel member snapshot. Also used for energy levels (only `user_id` and `energy` set).
 */
typedef struct AurixParticipant {
  struct AurixUuid user_id;
  uint32_t ssrc;
  enum AurixRole role;
  bool muted;
  bool server_muted;
  bool speaking;
  /**
   * `0..=1`.
   */
  float energy;
  /**
   * UTF-8, NUL-terminated, truncated to fit.
   */
  char display_name[AURIX_NAME_LEN];
} AurixParticipant;

/**
 * Chat message (strings owned by the event).
 */
typedef struct AurixChatMessage {
  struct AurixUuid message_id;
  /**
   * Zero UUID for directed messages.
   */
  struct AurixUuid channel_id;
  struct AurixUuid sender_id;
  /**
   * Zero UUID for channel messages.
   */
  struct AurixUuid recipient_id;
  const char *sender_name;
  const char *text;
  /**
   * JSON or `NULL`.
   */
  const char *metadata_json;
  /**
   * Unix milliseconds.
   */
  int64_t sent_at_ms;
  /**
   * Non-zero when this is the echo of a message this client sent.
   */
  uint64_t request_id;
} AurixChatMessage;

typedef struct AurixTranscript {
  struct AurixUuid channel_id;
  struct AurixUuid user_id;
  const char *text;
  /**
   * BCP-47 or `NULL`.
   */
  const char *language;
  /**
   * Server clock, Unix milliseconds.
   */
  int64_t started_at_ms;
  uint32_t duration_ms;
  /**
   * Word timings are available through `aurix_event_json`.
   */
  uint32_t word_count;
} AurixTranscript;

typedef struct AurixTtsStatus {
  /**
   * Id returned by `aurix_client_speak`, 0 if the request was not made by this client.
   */
  uint64_t request_id;
  struct AurixUuid server_request_id;
  enum AurixTtsState state;
  uint32_t duration_ms;
  /**
   * Failure detail or `NULL`.
   */
  const char *message;
} AurixTtsStatus;

/**
 * How far presence and text reach in a positional channel (`PositionalConfig.roster_radius` /
 * `text_radius`). A radius `<= 0` means "the whole channel".
 */
typedef struct AurixChannelScope {
  /**
   * The roster only lists members within this distance of us (once both positions are
   * known); `ParticipantJoined`/`ParticipantLeft` also fire when someone moves in or out
   * of range (leaving uses a 10 % wider radius so the edge does not flicker).
   */
  float roster_radius;
  /**
   * Channel chat, typing and transcripts reach only members within this distance.
   */
  float text_radius;
} AurixChannelScope;

/**
 * Membership facts of a joined channel.
 */
typedef struct AurixChannelInfo {
  /**
   * This session's role; `AurixRoleListener` cannot transmit (the server drops its frames).
   */
  enum AurixRole role;
  /**
   * Members across all nodes, including listeners hidden from the roster.
   */
  uint32_t participant_count;
  /**
   * Receive-only listeners are absent from the roster and never announced.
   */
  bool hidden_listeners;
  /**
   * Speech is transcribed and captions delivered.
   */
  bool transcription;
  /**
   * Speech is analysed by the content-safety classifier (disclose it).
   */
  bool safety_voice;
} AurixChannelInfo;

/**
 * Runtime DSP diagnostics.
 */
typedef struct AurixDspStats {
  /**
   * Echo return loss enhancement of the linear filter (dB) while the far end is active.
   */
  float erle_db;
  /**
   * Playback→capture delay the echo canceller is aligned to (ms).
   */
  uint32_t echo_delay_ms;
  /**
   * The adaptive filter has seen enough far-end audio to have converged.
   */
  bool echo_converged;
  /**
   * Rendered audio was fed in the last second.
   */
  bool far_end_active;
  /**
   * Speech probability of the last 10 ms block (`0..=1`).
   */
  float speech_probability;
  /**
   * Current AGC gain (dB; 0 when AGC is off).
   */
  float agc_gain_db;
  /**
   * Blocks processed without reference audio while the AEC was on and being fed.
   */
  uint64_t far_end_underruns;
} AurixDspStats;

/**
 * A channel's audio policy as set by the operator (`ChannelConfig`), merged across the
 * joined channels. `complexity < 0` = no hint.
 */
typedef struct AurixAudioPolicy {
  /**
   * Target uplink bitrate.
   */
  uint32_t bitrate_bps;
  /**
   * Floor the server's adaptive bitrate never goes below.
   */
  uint32_t min_bitrate_bps;
  bool fec;
  bool dtx;
  enum AurixOpusBandwidth max_bandwidth;
  int8_t complexity;
  enum AurixOpusSignal signal;
  /**
   * Senders may encode two channels (stereo music / broadcast); `false` asks for mono.
   */
  bool stereo;
} AurixAudioPolicy;

/**
 * Pose of one user for positional channels (engine coordinates; the channel config decides
 * handedness).
 */
typedef struct AurixPosition {
  struct AurixUuid user_id;
  float x;
  float y;
  float z;
  float forward_x;
  float forward_y;
  float forward_z;
  float up_x;
  float up_y;
  float up_z;
} AurixPosition;

/**
 * Server-side view of the connection in both directions. `bars` is `1..=5`
 * (R ≥ 80/70/60/50 → 5/4/3/2, else 1); loss values are percentages.
 */
typedef struct AurixNetworkQuality {
  uint8_t bars;
  float r_factor;
  float mos;
  float rtt_ms;
  float downlink_jitter_ms;
  float downlink_loss_percent;
  float uplink_jitter_ms;
  float uplink_loss_percent;
  uint32_t uplink_bitrate_kbps;
  uint64_t uplink_packets_received;
  uint64_t uplink_packets_lost;
} AurixNetworkQuality;

/**
 * Transport and codec counters for a network-quality indicator. Counters are lifetime
 * totals; `loss_percent`, `r_factor`, `mos` and `bars` describe the last quality period.
 */
typedef struct AurixStats {
  uint64_t packets_sent;
  uint64_t bytes_sent;
  uint64_t packets_received;
  uint64_t bytes_received;
  uint64_t audio_frames_received;
  /**
   * Packets that failed authentication (tampering or a stale key).
   */
  uint64_t bad_auth;
  uint64_t replayed;
  uint64_t heartbeats_lost;
  /**
   * Downlink frames concealed (PLC), discarded as late, and jitter-buffer underruns.
   */
  uint64_t frames_lost;
  uint64_t frames_late;
  uint64_t underruns;
  uint64_t frames_encoded;
  uint64_t frames_sent;
  uint64_t frames_gated;
  /**
   * Last heartbeat RTT plus min/avg/max over the session (0 until the first ack).
   */
  float rtt_ms;
  float rtt_min_ms;
  float rtt_avg_ms;
  float rtt_max_ms;
  float jitter_ms;
  /**
   * Downlink loss over the last quality period, as a percentage (`0..=100`).
   */
  float loss_percent;
  /**
   * Client-measured downlink quality; `bars` is `1..=5`.
   */
  float r_factor;
  float mos;
  uint8_t bars;
  /**
   * `true` when `server` holds the latest server-reported quality.
   */
  bool has_server;
  struct AurixNetworkQuality server;
  /**
   * Remote streams currently decoding.
   */
  uint32_t active_streams;
  /**
   * Link the media currently uses.
   */
  enum AurixMediaPath media_path;
  /**
   * Tunnel only: uplink packets dropped because the WebSocket could not keep up.
   */
  uint64_t uplink_dropped;
  /**
   * Heartbeats unanswered in a row on the current link (0 = healthy).
   */
  uint32_t heartbeats_lost_consecutive;
} AurixStats;

/**
 * One advertised region (`GET /v1/me/regions`, `endpoint` of `POST /v1/tokens`): the
 * least-loaded healthy node of the region that has a public WebSocket URL.
 */
typedef struct AurixRegionEndpoint {
  /**
   * Region name as the API spells it (`us_east`, `eu_west`, ...), NUL-terminated.
   */
  char region[AURIX_NAME_LEN];
  struct AurixUuid node_id;
  /**
   * Direct `wss://` URL of the node; use it as `AurixClientConfig::ws_url`.
   */
  char ws_url[AURIX_URL_LEN];
  /**
   * `GET` target for RTT probing (answered by exactly this node); empty when not public.
   */
  char probe_url[AURIX_URL_LEN];
  bool has_location;
  double latitude;
  double longitude;
  /**
   * Great-circle distance from the location hint when both were known, else `false`.
   */
  bool has_distance;
  double distance_km;
  /**
   * Nodes with capacity in the region.
   */
  uint32_t nodes;
  /**
   * Load of the advertised node, `0..1`.
   */
  float load_factor;
  /**
   * `true` after `aurix_regions_set_rtt` with a non-negative value.
   */
  bool has_rtt;
  double rtt_ms;
  /**
   * `true` after `aurix_regions_set_rtt` with a negative value (unreachable).
   */
  bool probe_failed;
} AurixRegionEndpoint;



#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Message of the last error raised on the calling thread (empty string if none).
 * Valid until the next failing call on this thread.
 */
const char *aurix_last_error(void);

/**
 * Library version (`CARGO_PKG_VERSION`), static.
 */
const char *aurix_version(void);

/**
 * Parse a canonical/hyphenated/simple UUID string.
 */
enum AurixResult aurix_uuid_parse(const char *text, struct AurixUuid *out);

/**
 * Write the hyphenated form into `out` (at least `AURIX_UUID_STRING_LEN` bytes incl. NUL).
 */
enum AurixResult aurix_uuid_format(const struct AurixUuid *id, char *out, size_t out_len);

bool aurix_is_synthesized_ssrc(uint32_t ssrc);

uint32_t aurix_source_ssrc(uint32_t ssrc);

void aurix_client_config_default(struct AurixClientConfig *out);

/**
 * Everything on (high-pass, AEC with a 200 ms tail, high noise suppression, AGC to -18 dBFS).
 */
void aurix_dsp_config_default(struct AurixDspConfig *out);

/**
 * Everything off: the capture stream reaches the VAD/encoder untouched.
 */
void aurix_dsp_config_bypass(struct AurixDspConfig *out);

/**
 * Create a client. Returns `NULL` (see `aurix_last_error`) if the config is invalid or the
 * runtime/codec cannot be initialised. Does not connect.
 */
struct AurixClient *aurix_client_create(const struct AurixClientConfig *config);

/**
 * Disconnect (if needed) and free the handle. Do not call from the wake callback.
 */
void aurix_client_destroy(struct AurixClient *client);

/**
 * Start connecting; progress is reported through events. Idempotent while connected.
 */
enum AurixResult aurix_client_connect(struct AurixClient *client);

/**
 * Close the session for good (blocks up to ~3 s for the server to acknowledge).
 */
void aurix_client_disconnect(struct AurixClient *client);

/**
 * Replace the session token used for the next connect/reconnect and for re-joins.
 */
enum AurixResult aurix_client_set_token(struct AurixClient *client, const char *token);

enum AurixConnectionState aurix_client_state(const struct AurixClient *client);

/**
 * `false` when no session is open.
 */
bool aurix_client_session(const struct AurixClient *client, struct AurixSessionInfo *out);

/**
 * WebSocket URL of the node serving (or last serving) the session — `AurixConfig.ws_url`
 * until a failover moved it. Returns the number of bytes needed (excluding NUL); `buf` may
 * be `NULL` to size it. 0 for an invalid handle.
 */
size_t aurix_client_endpoint(const struct AurixClient *client, char *buf, size_t capacity);

/**
 * Number of alternate nodes advertised by the server for this session (tried in order,
 * after the current node, when the connection drops).
 */
size_t aurix_client_failover_endpoint_count(const struct AurixClient *client);

/**
 * The `index`-th failover URL (see `aurix_client_failover_endpoint_count`); same buffer
 * contract as `aurix_client_endpoint`. 0 when `index` is out of range.
 */
size_t aurix_client_failover_endpoint(const struct AurixClient *client,
                                      size_t index,
                                      char *buf,
                                      size_t capacity);

/**
 * Link the media currently uses; `AurixMediaNone` before the first bind.
 */
enum AurixMediaPath aurix_client_media_path(const struct AurixClient *client);

/**
 * Next queued event or `NULL`. Caller owns the result (`aurix_event_free`).
 */
struct AurixEvent *aurix_client_poll_event(struct AurixClient *client);

/**
 * Block up to `timeout_ms` for the next event; `NULL` on timeout.
 */
struct AurixEvent *aurix_client_wait_event(struct AurixClient *client, uint32_t timeout_ms);

size_t aurix_client_pending_events(const struct AurixClient *client);

/**
 * Called on an internal thread whenever an event is queued (e.g. to wake the game thread).
 * Pass `NULL` to clear. Must not block or call `aurix_client_destroy`.
 */
void aurix_client_set_wake_callback(struct AurixClient *client,
                                    void (*callback)(void *user_data),
                                    void *user_data);

void aurix_event_free(struct AurixEvent *event);

enum AurixEventType aurix_event_type(const struct AurixEvent *event);

/**
 * Whole event as JSON (`{"type": …, "data": …}`); handy for logging and for `Positions`.
 * Owned by the event.
 */
const char *aurix_event_json(const struct AurixEvent *event);

enum AurixConnectionState aurix_event_state(const struct AurixEvent *event);

/**
 * Request id the event answers (`aurix_client_join_channel`, `moderate`, `send_chat`,
 * `speak`); 0 when unrelated to a request.
 */
uint64_t aurix_event_request_id(const struct AurixEvent *event);

/**
 * Channel the event concerns (zero UUID if none).
 */
struct AurixUuid aurix_event_channel_id(const struct AurixEvent *event);

/**
 * User the event concerns (zero UUID if none).
 */
struct AurixUuid aurix_event_user_id(const struct AurixEvent *event);

/**
 * Recording id for `Recording`, server request id for `TtsStatus`, message id for chat.
 */
struct AurixUuid aurix_event_object_id(const struct AurixEvent *event);

/**
 * Primary boolean of the event (muted / speaking / typing / blocked / active / resumed /
 * transcription — see `AurixEventType` docs).
 */
bool aurix_event_flag(const struct AurixEvent *event);

/**
 * Secondary boolean: `server_muted` for `ParticipantMuteChanged`, `live` for `Recording`,
 * `safety_voice` (content-safety monitoring, disclose it) for `ChannelJoined`, `migrated`
 * for `Recovered`.
 */
bool aurix_event_flag2(const struct AurixEvent *event);

/**
 * Numeric payload: bitrate (bps) for `BitrateChanged`, attempt for `Recovering`.
 */
uint64_t aurix_event_number(const struct AurixEvent *event);

/**
 * Secondary number: reconnect delay in ms for `Recovering`.
 */
uint64_t aurix_event_number2(const struct AurixEvent *event);

/**
 * Machine-readable code for failures (`RequestFailed`, `ServerError`, `RejoinFailed`);
 * empty otherwise. Owned by the event.
 */
const char *aurix_event_code(const struct AurixEvent *event);

/**
 * Human-readable text: error message, kick/disconnect reason, bitrate reason, reconnect
 * cause. Empty when not applicable. Owned by the event.
 */
const char *aurix_event_message(const struct AurixEvent *event);

enum AurixTransmissionMode aurix_event_transmission(const struct AurixEvent *event);

/**
 * Codec of an `AudioCodecChanged` event; Opus otherwise.
 */
enum AurixAudioCodec aurix_event_audio_codec(const struct AurixEvent *event);

/**
 * Mode of a `DownlinkModeChanged` event; `Streams` otherwise.
 */
enum AurixDownlinkMode aurix_event_downlink_mode(const struct AurixEvent *event);

/**
 * Link of a `MediaPathChanged` event; `AurixMediaNone` for other events.
 */
enum AurixMediaPath aurix_event_media_path(const struct AurixEvent *event);

enum AurixModerationAction aurix_event_moderation_action(const struct AurixEvent *event);

/**
 * Session facts for `SessionReady`.
 */
bool aurix_event_session(const struct AurixEvent *event, struct AurixSessionInfo *out);

/**
 * Number of entries readable with `aurix_event_participant` (roster on `ChannelJoined`,
 * one on `ParticipantJoined`, levels on `ChannelEnergy`).
 */
size_t aurix_event_participant_count(const struct AurixEvent *event);

bool aurix_event_participant(const struct AurixEvent *event,
                             size_t index,
                             struct AurixParticipant *out);

bool aurix_event_chat(const struct AurixEvent *event, struct AurixChatMessage *out);

bool aurix_event_transcript(const struct AurixEvent *event, struct AurixTranscript *out);

bool aurix_event_tts(const struct AurixEvent *event, struct AurixTtsStatus *out);

/**
 * Join `channel_id`. `join_token` may be `NULL` (session token rights apply). The request id
 * written to `request_id_out` is echoed by `ChannelJoined` / `RequestFailed`.
 */
enum AurixResult aurix_client_join_channel(struct AurixClient *client,
                                           const struct AurixUuid *channel_id,
                                           const char *join_token,
                                           uint64_t *request_id_out);

enum AurixResult aurix_client_leave_channel(struct AurixClient *client,
                                            const struct AurixUuid *channel_id);

/**
 * Copy up to `capacity` joined channel ids into `out`; returns the total number joined (may
 * exceed `capacity`).
 */
size_t aurix_client_joined_channels(const struct AurixClient *client,
                                    struct AurixUuid *out,
                                    size_t capacity);

/**
 * Whether speech in a joined channel is transcribed server-side (`Transcript` events).
 */
bool aurix_client_channel_transcribes(const struct AurixClient *client,
                                      const struct AurixUuid *channel_id);

/**
 * Whether speech in a joined channel is analysed by the server's content-safety classifier
 * (`ChannelJoinAck.safety_voice`); games should disclose it to the player.
 */
bool aurix_client_channel_monitored(const struct AurixClient *client,
                                    const struct AurixUuid *channel_id);

/**
 * Presence / text range of a joined channel; `false` (and `out` untouched) until its join
 * is acknowledged.
 */
bool aurix_client_channel_scope(const struct AurixClient *client,
                                const struct AurixUuid *channel_id,
                                struct AurixChannelScope *out);

/**
 * Role / member count / roster policy of a joined channel; `false` (and `out` untouched)
 * until its join is acknowledged.
 */
bool aurix_client_channel_info(const struct AurixClient *client,
                               const struct AurixUuid *channel_id,
                               struct AurixChannelInfo *out);

/**
 * `ChannelJoined` only: this session's role, the member count and the roster policy
 * (defaults for other events).
 */
struct AurixChannelInfo aurix_event_channel_info(const struct AurixEvent *event);

/**
 * `ChannelJoined` only: the channel's presence / text range (zeros for other events).
 */
struct AurixChannelScope aurix_event_channel_scope(const struct AurixEvent *event);

/**
 * Copy up to `capacity` participants of `channel_id`; returns the total count.
 */
size_t aurix_client_participants(const struct AurixClient *client,
                                 const struct AurixUuid *channel_id,
                                 struct AurixParticipant *out,
                                 size_t capacity);

/**
 * Owner of `ssrc` (microphone or its TTS voice) across joined channels.
 */
bool aurix_client_user_for_ssrc(const struct AurixClient *client,
                                uint32_t ssrc,
                                struct AurixUuid *out);

/**
 * Feed interleaved f32 capture PCM (`sample_count` total samples across channels) at any
 * sample rate. Encodes and sends 20 ms Opus frames. Audio-thread safe.
 */
void aurix_client_push_capture_f32(struct AurixClient *client,
                                   const float *pcm,
                                   size_t sample_count,
                                   uint32_t sample_rate,
                                   uint8_t channels);

void aurix_client_push_capture_i16(struct AurixClient *client,
                                   const int16_t *pcm,
                                   size_t sample_count,
                                   uint32_t sample_rate,
                                   uint8_t channels);

/**
 * Send a pre-encoded 20 ms Opus frame (engine-side encoder). `level` is the RFC 6464 level
 * byte (0 = loudest … 127 = silence) or -1 if unknown.
 */
enum AurixResult aurix_client_send_opus(struct AurixClient *client,
                                        const uint8_t *opus,
                                        size_t len,
                                        int32_t level);

/**
 * Mix all remote voices **into** `out` (interleaved f32, `sample_count` total samples,
 * `channels` 1 or 2; existing content is preserved and voices are added). Returns the
 * number of active streams. Audio-thread safe.
 */
size_t aurix_client_mix_output_f32(struct AurixClient *client,
                                   float *out,
                                   size_t sample_count,
                                   uint8_t channels);

/**
 * Like `aurix_client_mix_output_f32` but **overwrites** `out` with i16 samples.
 */
size_t aurix_client_mix_output_i16(struct AurixClient *client,
                                   int16_t *out,
                                   size_t sample_count,
                                   uint8_t channels);

void aurix_client_set_muted(struct AurixClient *client, bool muted);

bool aurix_client_is_muted(const struct AurixClient *client);

bool aurix_client_is_speaking(const struct AurixClient *client);

/**
 * Microphone software gain `0..=4`.
 */
void aurix_client_set_input_gain(struct AurixClient *client, float gain);

/**
 * RMS energy `0..=1` of the last captured frame.
 */
float aurix_client_input_energy(const struct AurixClient *client);

/**
 * Voice activity detector: RMS threshold `0..=1` and hangover in 20 ms frames.
 */
void aurix_client_set_vad(struct AurixClient *client, float threshold, uint32_t hangover_frames);

void aurix_client_set_vad_gate(struct AurixClient *client, bool enabled);

/**
 * Replace the capture DSP configuration (applies to the next frame; values are clamped —
 * read back with `aurix_client_dsp`). Changing the echo tail or delay hint resets the
 * echo canceller's filter.
 */
enum AurixResult aurix_client_set_dsp(struct AurixClient *client,
                                      const struct AurixDspConfig *config);

enum AurixResult aurix_client_dsp(const struct AurixClient *client, struct AurixDspConfig *out);

enum AurixResult aurix_client_dsp_stats(const struct AurixClient *client,
                                        struct AurixDspStats *out);

/**
 * Feed the echo canceller with audio the host plays through its own path (48 kHz,
 * interleaved, `sample_count` total samples). Audio the host obtains from
 * `aurix_client_mix_output_*` is fed automatically — do not push it again. Audio-thread safe.
 */
void aurix_client_push_render_f32(struct AurixClient *client,
                                  const float *pcm,
                                  size_t sample_count,
                                  uint8_t channels);

void aurix_client_push_render_i16(struct AurixClient *client,
                                  const int16_t *pcm,
                                  size_t sample_count,
                                  uint8_t channels);

enum AurixResult aurix_client_set_bitrate(struct AurixClient *client, uint32_t bitrate_bps);

/**
 * Replace the app's baseline encoder settings and re-apply them (under the current channel
 * policy when `follow_channel_policy` is on). Takes effect from the next frame.
 */
enum AurixResult aurix_client_set_encoder_settings(struct AurixClient *client,
                                                   const struct AurixEncoderSettings *settings);

/**
 * Settings the encoder is running with right now (after policy and server bitrate commands).
 */
bool aurix_client_encoder_settings(const struct AurixClient *client,
                                   struct AurixEncoderSettings *out);

/**
 * Pin Opus complexity `0..=10` regardless of channel hints (e.g. lower it on a weak CPU);
 * a negative value unpins and returns to the channel hint / config value.
 */
enum AurixResult aurix_client_set_complexity(struct AurixClient *client, int8_t complexity);

/**
 * Merged audio policy of the joined channels; `false` before the first join.
 */
bool aurix_client_audio_policy(const struct AurixClient *client, struct AurixAudioPolicy *out);

/**
 * Payload of `AurixEventAudioPolicyChanged`.
 */
bool aurix_event_audio_policy(const struct AurixEvent *event, struct AurixAudioPolicy *out);

/**
 * Master playback volume `0..=2`.
 */
void aurix_client_set_output_volume(struct AurixClient *client, float volume);

void aurix_client_set_output_muted(struct AurixClient *client, bool muted);

/**
 * Drop buffered capture samples (call after switching input devices).
 */
void aurix_client_reset_capture(struct AurixClient *client);

/**
 * Receiver-local mute of `user_id` in `channel_id` (or everywhere when `NULL`).
 */
enum AurixResult aurix_client_set_participant_mute(struct AurixClient *client,
                                                   const struct AurixUuid *user_id,
                                                   const struct AurixUuid *channel_id,
                                                   bool muted);

/**
 * Per-participant gain `0..=2` for this listener.
 */
enum AurixResult aurix_client_set_participant_volume(struct AurixClient *client,
                                                     const struct AurixUuid *user_id,
                                                     float volume);

/**
 * Persistent mutual block; acked by `UserBlockChanged`.
 */
enum AurixResult aurix_client_set_user_block(struct AurixClient *client,
                                             const struct AurixUuid *user_id,
                                             bool blocked);

/**
 * Which joined channels receive the microphone. `channel_id` is required for `Single`.
 */
enum AurixResult aurix_client_set_transmission(struct AurixClient *client,
                                               enum AurixTransmissionMode mode,
                                               const struct AurixUuid *channel_id);

/**
 * Focus one channel (others attenuated server-side); `NULL` clears.
 */
enum AurixResult aurix_client_set_channel_focus(struct AurixClient *client,
                                                const struct AurixUuid *channel_id);

/**
 * Ask the server to run this session on `codec`. PCMU (G.711 μ-law) is a low-CPU fallback
 * for weak devices: the node transcodes, so Opus participants of the same channel are
 * unaffected. Requires `media.pcmu_fallback` on the node (otherwise `ServerError`
 * `CODEC_NOT_AVAILABLE`); the switch takes effect on `AurixEventAudioCodecChanged`.
 */
enum AurixResult aurix_client_set_audio_codec(struct AurixClient *client,
                                              enum AurixAudioCodec codec);

/**
 * Codec the session currently uses (server-acknowledged).
 */
enum AurixAudioCodec aurix_client_audio_codec(const struct AurixClient *client);

/**
 * Ask the server to deliver other speakers as one mixed stereo stream per channel
 * (`AurixDownlinkMixed`) instead of one stream per speaker: constant downlink bandwidth and
 * decode cost in large channels. Mutes, volumes, focus, positional attenuation and panning
 * are applied by the node; E2EE speakers still arrive as separate streams. Requires
 * `media.downlink_mix` on the node (`AurixSessionInfo.downlink_mix`, otherwise `ServerError`
 * `DOWNLINK_MIX_NOT_AVAILABLE`); takes effect on `AurixEventDownlinkModeChanged`.
 */
enum AurixResult aurix_client_set_downlink_mode(struct AurixClient *client,
                                                enum AurixDownlinkMode mode);

/**
 * Downlink mode the server acknowledged.
 */
enum AurixDownlinkMode aurix_client_downlink_mode(const struct AurixClient *client);

enum AurixResult aurix_client_set_transcripts(struct AurixClient *client, bool enabled);

/**
 * Report 1..=64 poses for a positional channel.
 */
enum AurixResult aurix_client_update_positions(struct AurixClient *client,
                                               const struct AurixUuid *channel_id,
                                               const struct AurixPosition *positions,
                                               size_t count);

enum AurixResult aurix_client_respond_recording_consent(struct AurixClient *client,
                                                        const struct AurixUuid *recording_id,
                                                        enum AurixRecordingConsent consent);

/**
 * Escape hatch: send a raw client→server control message as JSON.
 */
enum AurixResult aurix_client_send_control_json(struct AurixClient *client, const char *json);

/**
 * Kick / mute / unmute with a one-time action token minted by the game backend.
 */
enum AurixResult aurix_client_moderate(struct AurixClient *client,
                                       const struct AurixUuid *channel_id,
                                       const struct AurixUuid *user_id,
                                       enum AurixModerationAction action,
                                       const char *action_token,
                                       const char *reason,
                                       uint64_t *request_id_out);

/**
 * Text message to a joined channel; `metadata_json` optional.
 */
enum AurixResult aurix_client_send_chat(struct AurixClient *client,
                                        const struct AurixUuid *channel_id,
                                        const char *text,
                                        const char *metadata_json,
                                        uint64_t *request_id_out);

/**
 * Directed message to one online user of the same application.
 */
enum AurixResult aurix_client_send_direct_chat(struct AurixClient *client,
                                               const struct AurixUuid *user_id,
                                               const char *text,
                                               const char *metadata_json,
                                               uint64_t *request_id_out);

enum AurixResult aurix_client_set_typing(struct AurixClient *client,
                                         const struct AurixUuid *channel_id,
                                         bool typing);

/**
 * Server-side text-to-speech as this participant's voice. `channel_id` may be `NULL` for
 * `Local`; `voice` may be `NULL` for the server default.
 */
enum AurixResult aurix_client_speak(struct AurixClient *client,
                                    const char *text,
                                    const struct AurixUuid *channel_id,
                                    enum AurixTtsDestination destination,
                                    const char *voice,
                                    uint64_t *request_id_out);

enum AurixResult aurix_client_cancel_speech(struct AurixClient *client);

enum AurixResult aurix_client_stats(const struct AurixClient *client, struct AurixStats *out);

/**
 * Latest server-reported quality. Returns `false` (and leaves `out` untouched) until the
 * server has sent its first report.
 */
bool aurix_client_network_quality(const struct AurixClient *client,
                                  struct AurixNetworkQuality *out);

/**
 * Payload of `AurixEventNetworkQuality`.
 */
bool aurix_event_network_quality(const struct AurixEvent *event, struct AurixNetworkQuality *out);

/**
 * Player-scoped discovery URL: `<api_url>/v1/me/regions` with optional `region` and
 * `latitude`/`longitude` hints (`has_location`). `preferred_region` may be `NULL`. Send it with
 * `Authorization: Bearer <player token>` from the engine's HTTP client, then pass the body to
 * `aurix_regions_parse`. Returns the number of bytes needed (excluding NUL); `buf` may be `NULL`.
 */
size_t aurix_regions_discovery_url(const char *api_url,
                                   const char *preferred_region,
                                   bool has_location,
                                   double latitude,
                                   double longitude,
                                   char *buf,
                                   size_t capacity);

/**
 * Parse a `GET /v1/me/regions` (or `/v1/regions`) body. Returns `NULL` (see `aurix_last_error`)
 * on malformed input. The list keeps the server order: preferred region first, then distance
 * (when a location hint was sent), then load.
 */
struct AurixRegionList *aurix_regions_parse(const char *json);

void aurix_regions_free(struct AurixRegionList *regions);

size_t aurix_regions_len(const struct AurixRegionList *regions);

/**
 * Copy entry `index` into `out`; `false` when out of range.
 */
bool aurix_regions_get(const struct AurixRegionList *regions,
                       size_t index,
                       struct AurixRegionEndpoint *out);

/**
 * Record the host's probe of entry `index` (best of a few `GET probe_url` samples after one
 * discarded warm-up): `rtt_ms >= 0` for a measurement, negative when every request failed.
 */
enum AurixResult aurix_regions_set_rtt(struct AurixRegionList *regions,
                                       size_t index,
                                       double rtt_ms);

/**
 * Re-rank in place after probing: `preferred_region` (may be `NULL`) first unless its probe
 * failed, then measured regions in ascending `rtt_tolerance_ms` buckets (`<= 0` selects the
 * default 15 ms), then unprobed regions, then unreachable ones; ties keep the server order.
 * Entry 0 is the recommendation.
 */
enum AurixResult aurix_regions_rank(struct AurixRegionList *regions,
                                    const char *preferred_region,
                                    double rtt_tolerance_ms);

/**
 * Create an Opus encoder for `sample_rate_hz` (8000/12000/16000/24000/48000) and 1 or 2
 * channels with `settings` (NULL = defaults). Returns NULL on error (see `aurix_last_error`).
 */
struct AurixOpusEncoder *aurix_opus_encoder_create(uint32_t sample_rate_hz,
                                                   uint8_t channels,
                                                   const struct AurixEncoderSettings *settings);

void aurix_opus_encoder_destroy(struct AurixOpusEncoder *encoder);

/**
 * Push new settings into the encoder; takes effect from the next frame. Out-of-range values
 * are clamped (read them back with `aurix_opus_encoder_settings`).
 */
enum AurixResult aurix_opus_encoder_apply(struct AurixOpusEncoder *encoder,
                                          const struct AurixEncoderSettings *settings);

/**
 * The settings the encoder is running with (as clamped).
 */
bool aurix_opus_encoder_settings(const struct AurixOpusEncoder *encoder,
                                 struct AurixEncoderSettings *out);

/**
 * Encode one interleaved f32 frame of `frame_samples_per_channel` samples per channel (a
 * valid Opus frame size: 2.5/5/10/20/40/60 ms). Returns the packet length written to `out`,
 * or a negative `AurixResult` code.
 */
int32_t aurix_opus_encoder_encode_f32(struct AurixOpusEncoder *encoder,
                                      const float *pcm,
                                      size_t frame_samples_per_channel,
                                      uint8_t *out,
                                      size_t out_len);

/**
 * `aurix_opus_encoder_encode_f32` for interleaved i16 PCM.
 */
int32_t aurix_opus_encoder_encode_i16(struct AurixOpusEncoder *encoder,
                                      const int16_t *pcm,
                                      size_t frame_samples_per_channel,
                                      uint8_t *out,
                                      size_t out_len);

/**
 * Create an Opus decoder for `sample_rate_hz` and 1 or 2 channels. NULL on error.
 */
struct AurixOpusDecoder *aurix_opus_decoder_create(uint32_t sample_rate_hz, uint8_t channels);

void aurix_opus_decoder_destroy(struct AurixOpusDecoder *decoder);

/**
 * Decode one packet into interleaved f32 PCM with room for `max_frame_samples_per_channel`
 * samples per channel. `packet == NULL` or `packet_len == 0` runs packet-loss concealment
 * for exactly `max_frame_samples_per_channel` samples. `fec` decodes the in-band FEC data
 * carried by `packet` for the *previous* (lost) frame instead of the packet's own audio.
 * Returns samples per channel written, or a negative `AurixResult` code.
 */
int32_t aurix_opus_decoder_decode_f32(struct AurixOpusDecoder *decoder,
                                      const uint8_t *packet,
                                      size_t packet_len,
                                      float *pcm,
                                      size_t max_frame_samples_per_channel,
                                      bool fec);

/**
 * `aurix_opus_decoder_decode_f32` for interleaved i16 PCM.
 */
int32_t aurix_opus_decoder_decode_i16(struct AurixOpusDecoder *decoder,
                                      const uint8_t *packet,
                                      size_t packet_len,
                                      int16_t *pcm,
                                      size_t max_frame_samples_per_channel,
                                      bool fec);

/**
 * Create a standalone DSP processor with `config` (NULL = `aurix_dsp_config_default`).
 */
struct AurixDsp *aurix_dsp_create(const struct AurixDspConfig *config);

void aurix_dsp_destroy(struct AurixDsp *dsp);

/**
 * Replace the configuration (clamped; read back with `aurix_dsp_config`).
 */
enum AurixResult aurix_dsp_set_config(struct AurixDsp *dsp, const struct AurixDspConfig *config);

enum AurixResult aurix_dsp_config(const struct AurixDsp *dsp, struct AurixDspConfig *out);

enum AurixResult aurix_dsp_stats(const struct AurixDsp *dsp, struct AurixDspStats *out);

/**
 * Process `sample_count` mono 48 kHz samples in place; `sample_count` must be a non-zero
 * multiple of `AURIX_DSP_BLOCK_SAMPLES`. Not thread-safe against itself; safe to call
 * concurrently with `aurix_dsp_push_render_f32`.
 */
enum AurixResult aurix_dsp_process_f32(struct AurixDsp *dsp, float *pcm, size_t sample_count);

/**
 * Echo-canceller reference: what the host is playing (48 kHz, interleaved `channels`,
 * `sample_count` total samples). Real-time thread safe; no-op while AEC is off.
 */
void aurix_dsp_push_render_f32(const struct AurixDsp *dsp,
                               const float *pcm,
                               size_t sample_count,
                               uint8_t channels);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AURIX_CLIENT_H */
