/* Aurix native voice client — stable C ABI. Generated by cbindgen from crates/aurix-client; do not edit (run `cargo run -p aurix-client --example gen_header`). */

#ifndef AURIX_CLIENT_H
#define AURIX_CLIENT_H

/* Generated with cbindgen:0.29.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Bytes needed for `aurix_uuid_format` (36 characters + NUL).
 */
#define AURIX_UUID_STRING_LEN 37

/**
 * Capacity of fixed-size UTF-8 name buffers in this ABI (including the NUL).
 */
#define AURIX_NAME_LEN 128

/**
 * Bit set on the SSRC of a synthesized (text-to-speech) voice; the base SSRC is the owner's.
 */
#define AURIX_SYNTH_SSRC_FLAG 2147483648

/**
 * Everything on the wire is Opus at 48 kHz; `mix_output` produces this rate.
 */
#define AURIX_SAMPLE_RATE 48000

/**
 * Samples per channel in one 20 ms frame at `AURIX_SAMPLE_RATE`.
 */
#define AURIX_FRAME_SAMPLES 960

/**
 * Capacity of fixed-size URL buffers in this ABI (including the NUL).
 */
#define AURIX_URL_LEN 512

/**
 * RTT differences below this are treated as ties (network noise, not a better region).
 */
#define DEFAULT_RTT_TOLERANCE_MS 15.0

/**
 * Return code of fallible calls; details via `aurix_last_error`.
 */
typedef enum AurixResult {
  AURIX_OK = 0,
  AURIX_NULL_POINTER = 1,
  AURIX_INVALID_ARGUMENT = 2,
  AURIX_NOT_CONNECTED = 3,
  AURIX_CLOSED = 4,
  AURIX_TRANSPORT = 5,
  AURIX_UNAUTHORIZED = 6,
  AURIX_TIMEOUT = 7,
  AURIX_SERVER_REJECTED = 8,
  AURIX_CODEC = 9,
  AURIX_PROTOCOL = 10,
} AurixResult;

typedef enum AurixConnectionState {
  AURIX_STATE_DISCONNECTED = 0,
  AURIX_STATE_CONNECTING = 1,
  AURIX_STATE_CONNECTED = 2,
  AURIX_STATE_MEDIA_BOUND = 3,
  AURIX_STATE_RECONNECTING = 4,
  AURIX_STATE_FAILED = 5,
} AurixConnectionState;

typedef enum AurixEventType {
  /**
   * `state`.
   */
  AURIX_EVENT_STATE_CHANGED = 0,
  /**
   * `session`.
   */
  AURIX_EVENT_SESSION_READY = 1,
  AURIX_EVENT_MEDIA_BOUND = 2,
  /**
   * `request_id`, `channel_id`, `participants`, `flag` = transcription enabled.
   */
  AURIX_EVENT_CHANNEL_JOINED = 3,
  /**
   * `channel_id`.
   */
  AURIX_EVENT_CHANNEL_LEFT = 4,
  /**
   * `channel_id`, `participants[0]`.
   */
  AURIX_EVENT_PARTICIPANT_JOINED = 5,
  /**
   * `channel_id`, `user_id`.
   */
  AURIX_EVENT_PARTICIPANT_LEFT = 6,
  /**
   * `channel_id`, `user_id`, `flag` = muted, `flag2` = server muted.
   */
  AURIX_EVENT_PARTICIPANT_MUTE_CHANGED = 7,
  /**
   * `channel_id`, `user_id`, `flag` = speaking.
   */
  AURIX_EVENT_PARTICIPANT_SPEAKING = 8,
  /**
   * `channel_id`, `participants[i].user_id/energy`.
   */
  AURIX_EVENT_CHANNEL_ENERGY = 9,
  /**
   * `flag` = speaking.
   */
  AURIX_EVENT_LOCAL_SPEAKING = 10,
  /**
   * `transmission`, `channel_id` for single.
   */
  AURIX_EVENT_TRANSMISSION_CHANGED = 11,
  /**
   * `channel_id` (zero UUID = no focus).
   */
  AURIX_EVENT_CHANNEL_FOCUS_CHANGED = 12,
  /**
   * `user_id`, `flag` = blocked.
   */
  AURIX_EVENT_USER_BLOCK_CHANGED = 13,
  /**
   * `channel_id`, `recording_id`, `flag` = active, `flag2` = live stream (not a stored
   * file), `user_id` = initiator (zero UUID = operator).
   */
  AURIX_EVENT_RECORDING = 14,
  /**
   * `number` = bitrate bps, `message` = reason.
   */
  AURIX_EVENT_BITRATE_CHANGED = 15,
  /**
   * `channel_id`, `message` = reason.
   */
  AURIX_EVENT_KICKED = 16,
  /**
   * `request_id`, `channel_id`, `user_id`, `moderation_action`.
   */
  AURIX_EVENT_MODERATION_APPLIED = 17,
  /**
   * `chat`.
   */
  AURIX_EVENT_CHAT_MESSAGE = 18,
  /**
   * `channel_id`, `user_id`, `flag` = typing.
   */
  AURIX_EVENT_PARTICIPANT_TYPING = 19,
  /**
   * `transcript`.
   */
  AURIX_EVENT_TRANSCRIPT = 20,
  /**
   * `tts`.
   */
  AURIX_EVENT_TTS_STATUS = 21,
  /**
   * `channel_id`, `positions` via `json`.
   */
  AURIX_EVENT_POSITIONS = 22,
  /**
   * `channel_id`, `code`, `message`.
   */
  AURIX_EVENT_REJOIN_FAILED = 23,
  /**
   * `request_id`, `code`, `message`.
   */
  AURIX_EVENT_REQUEST_FAILED = 24,
  /**
   * `code`, `message`.
   */
  AURIX_EVENT_SERVER_ERROR = 25,
  /**
   * `number` = attempt, `number2` = delay ms, `message` = cause.
   */
  AURIX_EVENT_RECOVERING = 26,
  /**
   * `flag` = resumed (else channels were re-joined with fresh state).
   */
  AURIX_EVENT_RECOVERED = 27,
  /**
   * `message` = reason.
   */
  AURIX_EVENT_FAILED_TO_RECOVER = 28,
  /**
   * `message` = reason.
   */
  AURIX_EVENT_DISCONNECTED = 29,
  /**
   * `network_quality`.
   */
  AURIX_EVENT_NETWORK_QUALITY = 30,
} AurixEventType;

typedef enum AurixTransmissionMode {
  /**
   * Microphone reaches no channel.
   */
  AURIX_TRANSMIT_NONE = 0,
  /**
   * Microphone reaches one channel (`channel_id` argument).
   */
  AURIX_TRANSMIT_SINGLE = 1,
  /**
   * Microphone reaches every joined channel.
   */
  AURIX_TRANSMIT_ALL = 2,
} AurixTransmissionMode;

typedef enum AurixModerationAction {
  AURIX_MODERATION_KICK = 0,
  AURIX_MODERATION_MUTE = 1,
  AURIX_MODERATION_UNMUTE = 2,
} AurixModerationAction;

typedef enum AurixRole {
  AURIX_ROLE_LISTENER = 0,
  AURIX_ROLE_SPEAKER = 1,
  AURIX_ROLE_MODERATOR = 2,
  AURIX_ROLE_ADMINISTRATOR = 3,
} AurixRole;

typedef enum AurixTtsState {
  AURIX_TTS_QUEUED = 0,
  AURIX_TTS_PLAYING = 1,
  AURIX_TTS_FINISHED = 2,
  AURIX_TTS_CANCELLED = 3,
  AURIX_TTS_FAILED = 4,
} AurixTtsState;

typedef enum AurixRecordingConsent {
  AURIX_CONSENT_ACCEPTED = 0,
  AURIX_CONSENT_DECLINED = 1,
} AurixRecordingConsent;

typedef enum AurixTtsDestination {
  /**
   * Heard by the channel (as this participant's voice) and locally.
   */
  AURIX_TTS_BOTH = 0,
  AURIX_TTS_CHANNEL = 1,
  AURIX_TTS_LOCAL = 2,
} AurixTtsDestination;

/**
 * Opaque voice client. One per player/session.
 */
typedef struct AurixClient AurixClient;

/**
 * Opaque event; read with the `aurix_event_*` accessors and release with `aurix_event_free`.
 */
typedef struct AurixEvent AurixEvent;

/**
 * Opaque, mutable list of regions; release with `aurix_regions_free`.
 */
typedef struct AurixRegionList AurixRegionList;

/**
 * 128-bit id (session, channel, user, recording) in RFC 4122 byte order.
 */
typedef struct AurixUuid {
  uint8_t bytes[16];
} AurixUuid;

/**
 * Connection parameters. Fill with `aurix_client_config_default`, then set `ws_url`/`token`.
 */
typedef struct AurixClientConfig {
  /**
   * `ws://host:port/ws` or `wss://…` (required, borrowed).
   */
  const char *ws_url;
  /**
   * Session JWT or one-time `login` action token (required, borrowed; copied).
   */
  const char *token;
  bool auto_reconnect;
  /**
   * 0 = never give up.
   */
  uint32_t reconnect_max_attempts;
  uint32_t reconnect_initial_delay_ms;
  uint32_t reconnect_max_delay_ms;
  uint32_t request_timeout_ms;
  uint32_t ping_interval_ms;
  uint32_t heartbeat_interval_ms;
  /**
   * Opus target bitrate, 6000..=128000.
   */
  uint32_t bitrate_bps;
  /**
   * Jitter buffer depth before playout starts (20 ms frames).
   */
  uint32_t jitter_target_frames;
  uint32_t jitter_max_frames;
  /**
   * Only send frames the voice activity detector marks as speech.
   */
  bool vad_gate;
  /**
   * Tokio worker threads for the control plane (1 is plenty).
   */
  uint32_t worker_threads;
} AurixClientConfig;

/**
 * Facts about the current session.
 */
typedef struct AurixSessionInfo {
  struct AurixUuid session_id;
  /**
   * This client's own SSRC (also the base of its TTS voice SSRC).
   */
  uint32_t ssrc;
  /**
   * How long the server keeps the session resumable after a drop.
   */
  uint32_t resume_grace_ms;
  /**
   * The latest (re)connect resumed the previous session.
   */
  bool resumed;
  /**
   * Zero UUID when the token carries no `sub`.
   */
  struct AurixUuid user_id;
} AurixSessionInfo;

/**
 * Channel member snapshot. Also used for energy levels (only `user_id` and `energy` set).
 */
typedef struct AurixParticipant {
  struct AurixUuid user_id;
  uint32_t ssrc;
  enum AurixRole role;
  bool muted;
  bool server_muted;
  bool speaking;
  /**
   * `0..=1`.
   */
  float energy;
  /**
   * UTF-8, NUL-terminated, truncated to fit.
   */
  char display_name[AURIX_NAME_LEN];
} AurixParticipant;

/**
 * Chat message (strings owned by the event).
 */
typedef struct AurixChatMessage {
  struct AurixUuid message_id;
  /**
   * Zero UUID for directed messages.
   */
  struct AurixUuid channel_id;
  struct AurixUuid sender_id;
  /**
   * Zero UUID for channel messages.
   */
  struct AurixUuid recipient_id;
  const char *sender_name;
  const char *text;
  /**
   * JSON or `NULL`.
   */
  const char *metadata_json;
  /**
   * Unix milliseconds.
   */
  int64_t sent_at_ms;
  /**
   * Non-zero when this is the echo of a message this client sent.
   */
  uint64_t request_id;
} AurixChatMessage;

typedef struct AurixTranscript {
  struct AurixUuid channel_id;
  struct AurixUuid user_id;
  const char *text;
  /**
   * BCP-47 or `NULL`.
   */
  const char *language;
  /**
   * Server clock, Unix milliseconds.
   */
  int64_t started_at_ms;
  uint32_t duration_ms;
  /**
   * Word timings are available through `aurix_event_json`.
   */
  uint32_t word_count;
} AurixTranscript;

typedef struct AurixTtsStatus {
  /**
   * Id returned by `aurix_client_speak`, 0 if the request was not made by this client.
   */
  uint64_t request_id;
  struct AurixUuid server_request_id;
  enum AurixTtsState state;
  uint32_t duration_ms;
  /**
   * Failure detail or `NULL`.
   */
  const char *message;
} AurixTtsStatus;

/**
 * Pose of one user for positional channels (engine coordinates; the channel config decides
 * handedness).
 */
typedef struct AurixPosition {
  struct AurixUuid user_id;
  float x;
  float y;
  float z;
  float forward_x;
  float forward_y;
  float forward_z;
  float up_x;
  float up_y;
  float up_z;
} AurixPosition;

/**
 * Server-side view of the connection in both directions. `bars` is `1..=5`
 * (R ≥ 80/70/60/50 → 5/4/3/2, else 1); loss values are percentages.
 */
typedef struct AurixNetworkQuality {
  uint8_t bars;
  float r_factor;
  float mos;
  float rtt_ms;
  float downlink_jitter_ms;
  float downlink_loss_percent;
  float uplink_jitter_ms;
  float uplink_loss_percent;
  uint32_t uplink_bitrate_kbps;
  uint64_t uplink_packets_received;
  uint64_t uplink_packets_lost;
} AurixNetworkQuality;

/**
 * Transport and codec counters for a network-quality indicator. Counters are lifetime
 * totals; `loss_percent`, `r_factor`, `mos` and `bars` describe the last quality period.
 */
typedef struct AurixStats {
  uint64_t packets_sent;
  uint64_t bytes_sent;
  uint64_t packets_received;
  uint64_t bytes_received;
  uint64_t audio_frames_received;
  /**
   * Packets that failed authentication (tampering or a stale key).
   */
  uint64_t bad_auth;
  uint64_t replayed;
  uint64_t heartbeats_lost;
  /**
   * Downlink frames concealed (PLC), discarded as late, and jitter-buffer underruns.
   */
  uint64_t frames_lost;
  uint64_t frames_late;
  uint64_t underruns;
  uint64_t frames_encoded;
  uint64_t frames_sent;
  uint64_t frames_gated;
  /**
   * Last heartbeat RTT plus min/avg/max over the session (0 until the first ack).
   */
  float rtt_ms;
  float rtt_min_ms;
  float rtt_avg_ms;
  float rtt_max_ms;
  float jitter_ms;
  /**
   * Downlink loss over the last quality period, as a percentage (`0..=100`).
   */
  float loss_percent;
  /**
   * Client-measured downlink quality; `bars` is `1..=5`.
   */
  float r_factor;
  float mos;
  uint8_t bars;
  /**
   * `true` when `server` holds the latest server-reported quality.
   */
  bool has_server;
  struct AurixNetworkQuality server;
  /**
   * Remote streams currently decoding.
   */
  uint32_t active_streams;
} AurixStats;

/**
 * One advertised region (`GET /v1/me/regions`, `endpoint` of `POST /v1/tokens`): the
 * least-loaded healthy node of the region that has a public WebSocket URL.
 */
typedef struct AurixRegionEndpoint {
  /**
   * Region name as the API spells it (`us_east`, `eu_west`, ...), NUL-terminated.
   */
  char region[AURIX_NAME_LEN];
  struct AurixUuid node_id;
  /**
   * Direct `wss://` URL of the node; use it as `AurixClientConfig::ws_url`.
   */
  char ws_url[AURIX_URL_LEN];
  /**
   * `GET` target for RTT probing (answered by exactly this node); empty when not public.
   */
  char probe_url[AURIX_URL_LEN];
  bool has_location;
  double latitude;
  double longitude;
  /**
   * Great-circle distance from the location hint when both were known, else `false`.
   */
  bool has_distance;
  double distance_km;
  /**
   * Nodes with capacity in the region.
   */
  uint32_t nodes;
  /**
   * Load of the advertised node, `0..1`.
   */
  float load_factor;
  /**
   * `true` after `aurix_regions_set_rtt` with a non-negative value.
   */
  bool has_rtt;
  double rtt_ms;
  /**
   * `true` after `aurix_regions_set_rtt` with a negative value (unreachable).
   */
  bool probe_failed;
} AurixRegionEndpoint;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Message of the last error raised on the calling thread (empty string if none).
 * Valid until the next failing call on this thread.
 */
const char *aurix_last_error(void);

/**
 * Library version (`CARGO_PKG_VERSION`), static.
 */
const char *aurix_version(void);

/**
 * Parse a canonical/hyphenated/simple UUID string.
 */
enum AurixResult aurix_uuid_parse(const char *text, struct AurixUuid *out);

/**
 * Write the hyphenated form into `out` (at least `AURIX_UUID_STRING_LEN` bytes incl. NUL).
 */
enum AurixResult aurix_uuid_format(const struct AurixUuid *id, char *out, size_t out_len);

bool aurix_is_synthesized_ssrc(uint32_t ssrc);

uint32_t aurix_source_ssrc(uint32_t ssrc);

void aurix_client_config_default(struct AurixClientConfig *out);

/**
 * Create a client. Returns `NULL` (see `aurix_last_error`) if the config is invalid or the
 * runtime/codec cannot be initialised. Does not connect.
 */
struct AurixClient *aurix_client_create(const struct AurixClientConfig *config);

/**
 * Disconnect (if needed) and free the handle. Do not call from the wake callback.
 */
void aurix_client_destroy(struct AurixClient *client);

/**
 * Start connecting; progress is reported through events. Idempotent while connected.
 */
enum AurixResult aurix_client_connect(struct AurixClient *client);

/**
 * Close the session for good (blocks up to ~3 s for the server to acknowledge).
 */
void aurix_client_disconnect(struct AurixClient *client);

/**
 * Replace the session token used for the next connect/reconnect and for re-joins.
 */
enum AurixResult aurix_client_set_token(struct AurixClient *client, const char *token);

enum AurixConnectionState aurix_client_state(const struct AurixClient *client);

/**
 * `false` when no session is open.
 */
bool aurix_client_session(const struct AurixClient *client, struct AurixSessionInfo *out);

/**
 * Next queued event or `NULL`. Caller owns the result (`aurix_event_free`).
 */
struct AurixEvent *aurix_client_poll_event(struct AurixClient *client);

/**
 * Block up to `timeout_ms` for the next event; `NULL` on timeout.
 */
struct AurixEvent *aurix_client_wait_event(struct AurixClient *client, uint32_t timeout_ms);

size_t aurix_client_pending_events(const struct AurixClient *client);

/**
 * Called on an internal thread whenever an event is queued (e.g. to wake the game thread).
 * Pass `NULL` to clear. Must not block or call `aurix_client_destroy`.
 */
void aurix_client_set_wake_callback(struct AurixClient *client,
                                    void (*callback)(void *user_data),
                                    void *user_data);

void aurix_event_free(struct AurixEvent *event);

enum AurixEventType aurix_event_type(const struct AurixEvent *event);

/**
 * Whole event as JSON (`{"type": …, "data": …}`); handy for logging and for `Positions`.
 * Owned by the event.
 */
const char *aurix_event_json(const struct AurixEvent *event);

enum AurixConnectionState aurix_event_state(const struct AurixEvent *event);

/**
 * Request id the event answers (`aurix_client_join_channel`, `moderate`, `send_chat`,
 * `speak`); 0 when unrelated to a request.
 */
uint64_t aurix_event_request_id(const struct AurixEvent *event);

/**
 * Channel the event concerns (zero UUID if none).
 */
struct AurixUuid aurix_event_channel_id(const struct AurixEvent *event);

/**
 * User the event concerns (zero UUID if none).
 */
struct AurixUuid aurix_event_user_id(const struct AurixEvent *event);

/**
 * Recording id for `Recording`, server request id for `TtsStatus`, message id for chat.
 */
struct AurixUuid aurix_event_object_id(const struct AurixEvent *event);

/**
 * Primary boolean of the event (muted / speaking / typing / blocked / active / resumed /
 * transcription — see `AurixEventType` docs).
 */
bool aurix_event_flag(const struct AurixEvent *event);

/**
 * Secondary boolean: `server_muted` for `ParticipantMuteChanged`, `live` for `Recording`.
 */
bool aurix_event_flag2(const struct AurixEvent *event);

/**
 * Numeric payload: bitrate (bps) for `BitrateChanged`, attempt for `Recovering`.
 */
uint64_t aurix_event_number(const struct AurixEvent *event);

/**
 * Secondary number: reconnect delay in ms for `Recovering`.
 */
uint64_t aurix_event_number2(const struct AurixEvent *event);

/**
 * Machine-readable code for failures (`RequestFailed`, `ServerError`, `RejoinFailed`);
 * empty otherwise. Owned by the event.
 */
const char *aurix_event_code(const struct AurixEvent *event);

/**
 * Human-readable text: error message, kick/disconnect reason, bitrate reason, reconnect
 * cause. Empty when not applicable. Owned by the event.
 */
const char *aurix_event_message(const struct AurixEvent *event);

enum AurixTransmissionMode aurix_event_transmission(const struct AurixEvent *event);

enum AurixModerationAction aurix_event_moderation_action(const struct AurixEvent *event);

/**
 * Session facts for `SessionReady`.
 */
bool aurix_event_session(const struct AurixEvent *event, struct AurixSessionInfo *out);

/**
 * Number of entries readable with `aurix_event_participant` (roster on `ChannelJoined`,
 * one on `ParticipantJoined`, levels on `ChannelEnergy`).
 */
size_t aurix_event_participant_count(const struct AurixEvent *event);

bool aurix_event_participant(const struct AurixEvent *event,
                             size_t index,
                             struct AurixParticipant *out);

bool aurix_event_chat(const struct AurixEvent *event, struct AurixChatMessage *out);

bool aurix_event_transcript(const struct AurixEvent *event, struct AurixTranscript *out);

bool aurix_event_tts(const struct AurixEvent *event, struct AurixTtsStatus *out);

/**
 * Join `channel_id`. `join_token` may be `NULL` (session token rights apply). The request id
 * written to `request_id_out` is echoed by `ChannelJoined` / `RequestFailed`.
 */
enum AurixResult aurix_client_join_channel(struct AurixClient *client,
                                           const struct AurixUuid *channel_id,
                                           const char *join_token,
                                           uint64_t *request_id_out);

enum AurixResult aurix_client_leave_channel(struct AurixClient *client,
                                            const struct AurixUuid *channel_id);

/**
 * Copy up to `capacity` joined channel ids into `out`; returns the total number joined (may
 * exceed `capacity`).
 */
size_t aurix_client_joined_channels(const struct AurixClient *client,
                                    struct AurixUuid *out,
                                    size_t capacity);

/**
 * Copy up to `capacity` participants of `channel_id`; returns the total count.
 */
size_t aurix_client_participants(const struct AurixClient *client,
                                 const struct AurixUuid *channel_id,
                                 struct AurixParticipant *out,
                                 size_t capacity);

/**
 * Owner of `ssrc` (microphone or its TTS voice) across joined channels.
 */
bool aurix_client_user_for_ssrc(const struct AurixClient *client,
                                uint32_t ssrc,
                                struct AurixUuid *out);

/**
 * Feed interleaved f32 capture PCM (`sample_count` total samples across channels) at any
 * sample rate. Encodes and sends 20 ms Opus frames. Audio-thread safe.
 */
void aurix_client_push_capture_f32(struct AurixClient *client,
                                   const float *pcm,
                                   size_t sample_count,
                                   uint32_t sample_rate,
                                   uint8_t channels);

void aurix_client_push_capture_i16(struct AurixClient *client,
                                   const int16_t *pcm,
                                   size_t sample_count,
                                   uint32_t sample_rate,
                                   uint8_t channels);

/**
 * Send a pre-encoded 20 ms Opus frame (engine-side encoder). `level` is the RFC 6464 level
 * byte (0 = loudest … 127 = silence) or -1 if unknown.
 */
enum AurixResult aurix_client_send_opus(struct AurixClient *client,
                                        const uint8_t *opus,
                                        size_t len,
                                        int32_t level);

/**
 * Mix all remote voices **into** `out` (interleaved f32, `sample_count` total samples,
 * `channels` 1 or 2; existing content is preserved and voices are added). Returns the
 * number of active streams. Audio-thread safe.
 */
size_t aurix_client_mix_output_f32(struct AurixClient *client,
                                   float *out,
                                   size_t sample_count,
                                   uint8_t channels);

/**
 * Like `aurix_client_mix_output_f32` but **overwrites** `out` with i16 samples.
 */
size_t aurix_client_mix_output_i16(struct AurixClient *client,
                                   int16_t *out,
                                   size_t sample_count,
                                   uint8_t channels);

void aurix_client_set_muted(struct AurixClient *client, bool muted);

bool aurix_client_is_muted(const struct AurixClient *client);

bool aurix_client_is_speaking(const struct AurixClient *client);

/**
 * Microphone software gain `0..=4`.
 */
void aurix_client_set_input_gain(struct AurixClient *client, float gain);

/**
 * RMS energy `0..=1` of the last captured frame.
 */
float aurix_client_input_energy(const struct AurixClient *client);

/**
 * Voice activity detector: RMS threshold `0..=1` and hangover in 20 ms frames.
 */
void aurix_client_set_vad(struct AurixClient *client, float threshold, uint32_t hangover_frames);

void aurix_client_set_vad_gate(struct AurixClient *client, bool enabled);

enum AurixResult aurix_client_set_bitrate(struct AurixClient *client, uint32_t bitrate_bps);

/**
 * Master playback volume `0..=2`.
 */
void aurix_client_set_output_volume(struct AurixClient *client, float volume);

void aurix_client_set_output_muted(struct AurixClient *client, bool muted);

/**
 * Drop buffered capture samples (call after switching input devices).
 */
void aurix_client_reset_capture(struct AurixClient *client);

/**
 * Receiver-local mute of `user_id` in `channel_id` (or everywhere when `NULL`).
 */
enum AurixResult aurix_client_set_participant_mute(struct AurixClient *client,
                                                   const struct AurixUuid *user_id,
                                                   const struct AurixUuid *channel_id,
                                                   bool muted);

/**
 * Per-participant gain `0..=2` for this listener.
 */
enum AurixResult aurix_client_set_participant_volume(struct AurixClient *client,
                                                     const struct AurixUuid *user_id,
                                                     float volume);

/**
 * Persistent mutual block; acked by `UserBlockChanged`.
 */
enum AurixResult aurix_client_set_user_block(struct AurixClient *client,
                                             const struct AurixUuid *user_id,
                                             bool blocked);

/**
 * Which joined channels receive the microphone. `channel_id` is required for `Single`.
 */
enum AurixResult aurix_client_set_transmission(struct AurixClient *client,
                                               enum AurixTransmissionMode mode,
                                               const struct AurixUuid *channel_id);

/**
 * Focus one channel (others attenuated server-side); `NULL` clears.
 */
enum AurixResult aurix_client_set_channel_focus(struct AurixClient *client,
                                                const struct AurixUuid *channel_id);

enum AurixResult aurix_client_set_transcripts(struct AurixClient *client, bool enabled);

/**
 * Report 1..=64 poses for a positional channel.
 */
enum AurixResult aurix_client_update_positions(struct AurixClient *client,
                                               const struct AurixUuid *channel_id,
                                               const struct AurixPosition *positions,
                                               size_t count);

enum AurixResult aurix_client_respond_recording_consent(struct AurixClient *client,
                                                        const struct AurixUuid *recording_id,
                                                        enum AurixRecordingConsent consent);

/**
 * Escape hatch: send a raw client→server control message as JSON.
 */
enum AurixResult aurix_client_send_control_json(struct AurixClient *client, const char *json);

/**
 * Kick / mute / unmute with a one-time action token minted by the game backend.
 */
enum AurixResult aurix_client_moderate(struct AurixClient *client,
                                       const struct AurixUuid *channel_id,
                                       const struct AurixUuid *user_id,
                                       enum AurixModerationAction action,
                                       const char *action_token,
                                       const char *reason,
                                       uint64_t *request_id_out);

/**
 * Text message to a joined channel; `metadata_json` optional.
 */
enum AurixResult aurix_client_send_chat(struct AurixClient *client,
                                        const struct AurixUuid *channel_id,
                                        const char *text,
                                        const char *metadata_json,
                                        uint64_t *request_id_out);

/**
 * Directed message to one online user of the same application.
 */
enum AurixResult aurix_client_send_direct_chat(struct AurixClient *client,
                                               const struct AurixUuid *user_id,
                                               const char *text,
                                               const char *metadata_json,
                                               uint64_t *request_id_out);

enum AurixResult aurix_client_set_typing(struct AurixClient *client,
                                         const struct AurixUuid *channel_id,
                                         bool typing);

/**
 * Server-side text-to-speech as this participant's voice. `channel_id` may be `NULL` for
 * `Local`; `voice` may be `NULL` for the server default.
 */
enum AurixResult aurix_client_speak(struct AurixClient *client,
                                    const char *text,
                                    const struct AurixUuid *channel_id,
                                    enum AurixTtsDestination destination,
                                    const char *voice,
                                    uint64_t *request_id_out);

enum AurixResult aurix_client_cancel_speech(struct AurixClient *client);

enum AurixResult aurix_client_stats(const struct AurixClient *client, struct AurixStats *out);

/**
 * Latest server-reported quality. Returns `false` (and leaves `out` untouched) until the
 * server has sent its first report.
 */
bool aurix_client_network_quality(const struct AurixClient *client,
                                  struct AurixNetworkQuality *out);

/**
 * Payload of `AurixEventNetworkQuality`.
 */
bool aurix_event_network_quality(const struct AurixEvent *event, struct AurixNetworkQuality *out);

/**
 * Player-scoped discovery URL: `<api_url>/v1/me/regions` with optional `region` and
 * `latitude`/`longitude` hints (`has_location`). `preferred_region` may be `NULL`. Send it with
 * `Authorization: Bearer <player token>` from the engine's HTTP client, then pass the body to
 * `aurix_regions_parse`. Returns the number of bytes needed (excluding NUL); `buf` may be `NULL`.
 */
size_t aurix_regions_discovery_url(const char *api_url,
                                   const char *preferred_region,
                                   bool has_location,
                                   double latitude,
                                   double longitude,
                                   char *buf,
                                   size_t capacity);

/**
 * Parse a `GET /v1/me/regions` (or `/v1/regions`) body. Returns `NULL` (see `aurix_last_error`)
 * on malformed input. The list keeps the server order: preferred region first, then distance
 * (when a location hint was sent), then load.
 */
struct AurixRegionList *aurix_regions_parse(const char *json);

void aurix_regions_free(struct AurixRegionList *regions);

size_t aurix_regions_len(const struct AurixRegionList *regions);

/**
 * Copy entry `index` into `out`; `false` when out of range.
 */
bool aurix_regions_get(const struct AurixRegionList *regions,
                       size_t index,
                       struct AurixRegionEndpoint *out);

/**
 * Record the host's probe of entry `index` (best of a few `GET probe_url` samples after one
 * discarded warm-up): `rtt_ms >= 0` for a measurement, negative when every request failed.
 */
enum AurixResult aurix_regions_set_rtt(struct AurixRegionList *regions,
                                       size_t index,
                                       double rtt_ms);

/**
 * Re-rank in place after probing: `preferred_region` (may be `NULL`) first unless its probe
 * failed, then measured regions in ascending `rtt_tolerance_ms` buckets (`<= 0` selects the
 * default 15 ms), then unprobed regions, then unreachable ones; ties keep the server order.
 * Entry 0 is the recommendation.
 */
enum AurixResult aurix_regions_rank(struct AurixRegionList *regions,
                                    const char *preferred_region,
                                    double rtt_tolerance_ms);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AURIX_CLIENT_H */
